### ISSUE TITLE
check hashes instead of file timestamps for the rebuild condition?

### ISSUE THREAD

**Issue by cboettig** [rstudio/blogdown#102]
If I have this right, blogdown applies a `make`-like rule for determining if an `.Rmd` file should be re-run.  Overall I think this is excellent (definitely better than relying on knitr caching, which would be too cumbersome in this case).   However, one thing that's always bothered me about `make` is that timestamps all get messed up by git operations such as changing between branches  in a directory (or when recovering from backups etc).  Seems to make more sense to just keep a quick log of file hashes to decide if a source file has changed more recently than its target (e.g. a la [remake](https://github.com/richfitz/remake) or many other make alternatives), since that would be much less fragile.  Maybe this is a lot more tricky then I'm realizing; and maybe most users won't be so concerned about just when & how their site rebuilds from scratch, but just wanted to bring it up.  

Meanwhile, might also be good to document the rebuild / not rebuild behavior more visibly.

**Comment by yihui** [comment]
That seems to be beyond the scope of blogdown since it is not an issue specific to blogdown. I don't know how to prevent git from changing the modification time of a file, but if you have time-consuming code chunks, I strongly recommend you to use other types of caching (either knitr caching or your own approach such as the good old `if (!exists('foo')) foo = readRDS('foo.rds')`). The caching mechanism based on modification times is more fragile than knitr's caching.

The rebuild behavior is documented at https://bookdown.org/yihui/blogdown/local-preview.html I don't think it is worth shouting out loud on this topic in the book, because I don't think most users even need to know about it since they won't use GIT branches.
