### ISSUE TITLE
Consider RcppTOML for parsing TOML?

### ISSUE THREAD

**Issue by thercast** [rstudio/blogdown#103]
I'm beginning to work on extending the new post addin as we discussed elsewhere and noticed that the `blogdown:::parse_toml` function is not picking up a lot of the params defined in my theme's archetype files for each type of post.  I just discovered [`RcppTOML`](http://dirk.eddelbuettel.com/code/rcpp.toml.html) and it looks like a great solution to deal with potentially complicated `toml` structures.  I realize that `blogdown` and by extension `rmarkdown` don't have `Rcpp` or any extensions of `Rcpp` as dependencies at this time, but as `blogdown` matures it may be worth incorporating `RcppTOML` to bring the parsing of `toml` on near equal footing to the `yaml` parsing that makes heavy use of the `yaml` package.

**Comment by yihui** [comment]
Thanks for the pointer. I don't really need a strict parser myself in this package, since I only need to read a very small number of top-level options. Anyway, I added RcppTOML to Suggests and `parse_toml()` will use it if installed.

For archetype files, I'd recommend you to convert them to YAML. IMHO the benefit of using TOML is totally trivial in Hugo. If your project is under version control (i.e. you are free to redo changes), you may run `hugo convert toYAML --unsafe` to convert all TOML to YAML, but I don't know if this applies to archetypes.

**Comment by thercast** [comment]
Thanks!  I did end up using `hugo convert toYAML --unsafe` to convert the `toml` frontmatter in my posts to `yaml` and that went through without a problem, but it did not touch the theme archetypes.  But I will investigate further.  I'm just thinking that most users of this package will find a theme they like and very likely will not touch the theme's infrastructure (although you and I both have done lots of customization with our site themes), so having `RcppTOML` is a great backup strategy to deal with non-converted theme/site files.
