### ISSUE TITLE
Download link/button for .Rmd file

### ISSUE THREAD

**Issue by stevenfazzio** [rstudio/blogdown#106]
It would be nice if there were a way to add a download link to each article so that the reader could download the .Rmd file associated with the article.

**Comment by cboettig** [comment]
I think this would be hard to implement robustly on the `blogdown` side, since the `.Rmd` file isn't transferred to Hugo's `publishDir` and so there's no obvious path to point to.  If your site source is hosted publicly (say, on GitHub) though it's easy enough to construct a URL in your Hugo template that will point to the the .Rmd there.  This is what I do with my site, e.g.: http://www.carlboettiger.info/2017/04/19/migrating-to-hugo-and-blogdown/

**Comment by apreshill** [comment]
If you are using Github, you can link to the Rmd file there as I did here:
https://apreshill.rbind.io/talk/code-your-graph/

**Comment by yihui** [comment]
If the website source repo is publicly available on Github, it is possible to automatically point to the Rmd source file on Github. I have documented how to include an "Edit this page" link on your website that takes readers to Github to edit an Rmd source file in the book: https://bookdown.org/yihui/blogdown/templates.html (search for "Github Edit" on this page).

If the website source repo is private, you may use `xfun::embed_file()`; see https://github.com/rstudio/rmarkdown/pull/708#issuecomment-403242508 for more info.
