### ISSUE TITLE
The system cannot find the path specified. status 65535

### ISSUE THREAD

**Issue by mikeyangpro** [rstudio/blogdown#156]
I thought I was having the exact same problem on https://stackoverflow.com/questions/44765205/new-post-will-not-create-an-rmarkdown-post-in-blogdown, so I've updated blogdown but I've still getting the error message when trying the build site.

```
Started building sites ...
ERROR 2017/07/18 13:52:51 Error while rendering "section": template: theme/section/about.html:4:3: executing "theme/section/about.html" at <partial "profile.htm...>: error calling partial: template: theme/partials/profile.html:8:38: executing "theme/partials/profile.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
Started building sites ...
ERROR 2017/07/18 13:52:52 Error while rendering "section": template: theme/section/about.html:4:3: executing "theme/section/about.html" at <partial "profile.htm...>: error calling partial: template: theme/partials/profile.html:8:38: executing "theme/partials/profile.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\Mike.Yang\AppData\Roaming\Hugo\hugo.exe" -d "../mikeyangpro.github.io" -t hugo-theme-cactus-plus' execution failed with error code 1
In addition: Warning messages:
1: running command '"C:\Users\Mike.Yang\AppData\Roaming\Hugo\hugo.exe" -d "../mikeyangpro.github.io" -t hugo-theme-cactus-plus' had status 65535 
2: running command '"C:\Users\Mike.Yang\AppData\Roaming\Hugo\hugo.exe" -d "../mikeyangpro.github.io" -t hugo-theme-cactus-plus' had status 65535 
3: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Users\Mike.Yang\AppData\Roaming\Hugo\hugo.exe" -d "../mikeyangpro.github.io" -t hugo-theme-cactus-plus' had status 1 
```

**Comment by yihui** [comment]
You used the `hugo-theme-cactus-plus` theme by @nodejh, which requires a `bio` parameter in config.toml: https://github.com/nodejh/hugo-theme-cactus-plus/blob/6d881da41466ca741c507a228af993a76df00097/layouts/partials/profile.html#L8

Like this: https://github.com/nodejh/hugo-theme-cactus-plus/blob/6d881da41466ca741c507a228af993a76df00097/exampleSite/config.toml#L14

I guess you didn't set it in your config.toml. As I said in the documentation https://bookdown.org/yihui/blogdown/other-themes.html, if you want to use a different theme, you'd better use `blogdown::new_site()` instead of manually install a theme. At least you have to read the theme's default example.

Anyway, I have submitted a PR to @nodejh to fix it on his side: https://github.com/nodejh/hugo-theme-cactus-plus/pull/17

**Comment by mikeyangpro** [comment]
Thanks! That worked for me.

**Comment by morandiaye** [comment]
Hi I have this problem whener i make my personal website
`Error: "C:\Users\pc\Desktop\projet\dfg\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
Error: "C:\Users\pc\Desktop\projet\dfg\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
Error: "C:\Users\pc\Desktop\projet\dfg\content\home\demo.md:39:1": failed to extract shortcode: template for shortcode "alert" not found
Error in shell(cmd, mustWork = TRUE, intern = intern) : 
  '"C:\Users\pc\AppData\Roaming\Hugo\hugo.exe" convert toYAML --unsafe' execution failed with error code 65535`

**Comment by yihui** [comment]
@mikeyangpro https://stackoverflow.com/q/63727355/559676
