### ISSUE TITLE
Expose a `change_theme` function or :::change_config()

### ISSUE THREAD

**Issue by drknexus** [rstudio/blogdown#162]
Currently the only way (I noticed at first glance) to change configs without diving into `config.toml` is to `blogdown::install_theme()`.  That helpfully has the default of `update_config = TRUE`.  However, if you want to go back and use a previously installed theme, without modifying `config.toml` by hand, it seems like you have to delete the theme directory and run `install_theme()` again.  For ease of use, it seems like an `update_theme()` or exposing `:::change_config()` would be great.  If you agree, but don't want to prioritize this, then I'd be glad to open a PR.

**Comment by yihui** [comment]
First, I think modifying the `theme` option in config.toml is actually easier than calling `blogdown::change_config('theme', 'theme-name')`. Second, changing themes is usually not as simple as updating this option, because different themes may have different requirements of config.toml. If you are just getting started with blogdown, I recommend you use `blogdown::new_site()` for reasons explained at https://bookdown.org/yihui/blogdown/other-themes.html. If you are familiar with blogdown and Hugo, I guess `change_theme()` or `change_config()` won't really offer much benefit.

**Comment by drknexus** [comment]
Alrighty, thanks!
