### ISSUE TITLE
Provide a way to generate .md output instead of .html

### ISSUE THREAD

**Issue by yihui** [rstudio/blogdown#165]
When the user does not really need Pandoc's Markdown, and the post does not contain HTML widgets, plain Markdown output may suffice and there is no need to go through Pandoc.

**Comment by znmeb** [comment]
Would it go through Hugo's Markdown processor then?

**Comment by yihui** [comment]
Yes.

**Comment by znmeb** [comment]
Sounds good to me.

**Comment by jemus42** [comment]
I'm currently trying to get table of contents to work with .Rmd posts, and I figured that my template's `{{ .TableOfContents }}` is ignored because Hugo only sees the generated html, so this would work in my favor as well and I won't need to open a separate issue about it (which is why I came here just now) \o/

**Comment by yihui** [comment]
@jemus42 Please see https://bookdown.org/yihui/blogdown/output-format.html for how to get a TOC for R Markdown posts.

**Comment by jemus42** [comment]
@yihui Yes, that works to get a basic toc, but that output does not match the toc as generated by hugo, and it's not possible to integrate it into my hugo template, which makes it both difficult to style and not match the tocs in other blogposts :/

**Comment by yihui** [comment]
Implemented. Use the filename extension `.Rmarkdown` instead of `.Rmd` to get Markdown output instead of HTML.
