### ISSUE TITLE
New Post addin: Select proper archetype

### ISSUE THREAD

**Issue by jemus42** [rstudio/blogdown#173]
It looks like the addin defaults to the `archetypes/default.md` archetype, however it should be using the `post.md` archetype or `page.md` archetype respectively if they exists, depending on the directory the post is placed in.

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by lcolladotor** [comment]
Hi,

I found this after digging further about the `kind` argument and the comment & answer at https://stackoverflow.com/questions/48844340/is-it-possible-to-create-a-rmd-file-template-for-the-blogdown-new-post-addin. It turns out that it doesn't seem to be working yet.

From https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/inst/scripts/new_post.R#L68 I see that `file` is not `NULL`. That matters because https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L264 runs `default_kind(file)`. `default_kind()` eventually then runs https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L204

If I start with this setup:

```R
> dir('archetypes')
[1] "default.md" "posts.md"
> path
[1] "/Users/lcollado/Dropbox/Code/hugoblog/content/post/2018-02-22-prueba6.Rmd"
```

then run most of `default_kind()` I find out that it's looking for `archetypes/.md`, not `archetypes/default.md` or other files like that.

```R
> path <- normalizePath(path, '/')
## Doesn't trigger first return() condition
> !grepl('/', path)
[1] FALSE
> atype <- gsub('/.*', '.md', path)
## md file, ok!
> atype
[1] ".md"
## Source of the problem!
> file.path('archetypes', atype)
[1] "archetypes/.md"
> file.exists(file.path('archetypes', atype))
[1] FALSE
```

One option maybe would be to do:

```R
if(!any(file.exists(dir('archetypes', pattern = atype, full.names = TRUE)))) return('default')
```

The last return() option https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/R/hugo.R#L205 probably needs to be a bit more complicated in case that it finds more than one file in `archetypes`.

Best,
Leo

**Comment by lcolladotor** [comment]
Regarding the `kind`, the RStudio addin could include a menu for choosing among the different archetypes it finds so that:

https://github.com/rstudio/blogdown/blob/a079068000fe86512503454f28dee49b486b3057/inst/scripts/new_post.R#L65-L70

would look like:

```R
blogdown::new_post(
          input$title, author = input$author, ext = input$format,
          categories = input$cat, tags = input$tag,
          file = gsub('[-[:space:]]+', '-', input$file),
          slug = input$slug, subdir = input$subdir, date = input$date,
          kind = input$kind
        )
```

and in the ui part:

```R
shiny::selectInput(inputId = 'kind', label = 'Archetype', choices = c('default', dir('archetypes', pattern = '.md$')))
```

or something fancier.

Best,
Leo
