### ISSUE TITLE
jpescador/hugo-future-imperfect not being maintained

### ISSUE THREAD

**Issue by norcalbiostat** [rstudio/blogdown#180]
According to https://github.com/jpescador/hugo-future-imperfect/issues/45 , the @jpescador repo for future-imperfect isn't being maintained and that the @hjiawei is the current version. 
You may want to update the theme chapter of the book documentation

**Comment by yihui** [comment]
Okay, I'll do that. Thanks for letting me know!

**Comment by pacollins** [comment]
There is a actually a slight split in versions. hjiawei and I are trying to reconcile the differences between our versions, but mine is currently the most update as it includes all of his updates in addition to newer features. I am currently working on cleaning up some of the depreciated code. Feel free to make PRs and Issues on my page just so that I can see them - hjiawei noted that he did't really intend to keep updating, but rather was just updating some dependencies for his own personal blog.

I will concede that I am not full out with git protocol yet, but I am pretty comfortable with hugo-future-imperfect.

**Comment by yihui** [comment]
I have removed this theme from the list in the book since its future is unclear to me.

**Comment by pacollins** [comment]
@yihui The process is moving quickly to transfer ownership. Feel free to follow on gohugoio/hugoThemes#285. If you'd like, I'll gladly keep you up to date.

**Comment by yihui** [comment]
@pacollins That will be great. Once someone can actively maintain this theme again, I can add it back to the book. Thanks!

**Comment by pacollins** [comment]
@yihui The theme has been updated if you could reinstate the theme. Thank you!
