### ISSUE TITLE
Rendering with full paths

### ISSUE THREAD

**Issue by dfalbel** [rstudio/blogdown#2]
Since I'm deploying gh-pages in a repo (not org.github.io repo), I'm not able to use relative paths. So I'm using `hugo -s .` to build the site.

By doing this, all assets like `javascripts` and `css` are linked with full path: `src="https://curso-r.github.io/verao2017/javascripts/application.js"` for example. 

This doesn't happen with images in Rmd files, they have a strange [link](https://github.com/curso-r/verao2017/blob/master/content/hello-world/index.html#L45): `src="#####../content/hello-world/index_files/figure-html/pie-1.png"`

How can I make blogdown render the html with baseurl param before the path to image instead of ` #####../content`?

This is my repo: 
https://github.com/curso-r/verao2017

And I'm using wercker to deploy the public folder to github pages.

Thanks in advance!

**Comment by dfalbel** [comment]
I fixed by just using: `knitr::opts_chunk$set(collapse = TRUE, fig.path = "")` in the .Rmd file 

Sorry!

**Comment by yihui** [comment]
Setting `fig.path=''` is probably not the ideal solution. I have not really started working on resolving paths other than paths for figures and HTML widgets yet, but the recommended way to build your website is not `hugo -s` in **blogdown**. I'm still working on the documentation, and typically you use `blogdown::serve_site()` to live preview your site, and you can just publish the site in the `public` folder. I'd recommend setting `relativeurls` to `true` in `config.yaml` or `config.toml`, so that your site will be portable (relative URLs everywhere so you can move your site wherever you want). Hugo seems to favor absolute paths, but I don't think it is a good idea.

**Comment by yihui** [comment]
FYI, I have renamed `render_pages()` to `build_site()` and exported it. You should not need to set `fig.path`.

**Comment by dfalbel** [comment]
Thanks! This will work great!

**Comment by dfalbel** [comment]
I think it's not exported yet :)

**Comment by yihui** [comment]
Indeed. Sorry about that. Just exported it.
