### ISSUE TITLE
Images don't show up

### ISSUE THREAD

**Issue by hmoazzem** [rstudio/blogdown#210]
Where should I keep images? Tried the Markdown `![optional caption text](figures/img.png)` syntax, but image doesn't show up. Preview in RStudio addin works perfect.
![](~/ws/blog/content/post/ttr.png)

**Comment by yihui** [comment]
Could you provide [a reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/)?

**Comment by hmoazzem** [comment]
Yes, I shared the HTML generated with RStudio Publish on [Rpub:](http://rpubs.com/moazzem/ttr-zoo)

**Comment by yihui** [comment]
You are asking a blogdown question, so you need to provide a reproducible example compiled through blogdown. The one you provided was compiled from rmarkdown instead.

Anyway, I guess I know what your problem is, and it is not related to blogdown. 
Please [ask the question on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead, with a reproducible example compiled through blogdown. Thanks!
