### ISSUE TITLE
Hugo now supports Pandoc

### ISSUE THREAD

**Issue by westernmagic** [rstudio/blogdown#237]
In https://github.com/rstudio/blogdown/blob/master/docs/02-hugo.Rmd you write:

> Besides, you have to use Hugo’s choice of the Markdown engine named “Blackfriday” instead of the more powerful Pandoc.

Seems that Hugo recently merged support for Pandoc!
https://github.com/gohugoio/hugo/pull/4060

**Comment by yihui** [comment]
Thanks for letting me know! This feature is not available in the released version of Hugo yet, but I looked at the PR, and my conclusion is that it is not very valuable, and you will have several advantages if you just use `.Rmd` instead of `.pandoc`. I just updated the documentation: https://bookdown.org/yihui/blogdown/static-sites.html (Footnote 21). I think the major disadvantage is that it will (significantly) slow down the rendering if you have a large number of Pandoc posts.
