### ISSUE TITLE
Redirected to absolute path 

### ISSUE THREAD

**Issue by d-notebook** [rstudio/blogdown#248]
I created a new website using the [beautifulhugo](https://github.com/halogenica/beautifulhugo ) theme.  
The example site created by the package has a `Tags` page, where the posts' tags with their frequency are correctly displayed. 
However, those tags redirect to a relative link (ie: http://tags/r-markdown/), instead of  (http://ip:port/tags/r-markdown/)

**Comment by yihui** [comment]
Sorry, but I can only handle Github issues for bug reports and feature requests, and usually I don't have time to answer general questions. Please [ask questions on StackOverflow](https://yihui.name/en/2017/08/so-gh-email/) instead (with minimal, self-contained, and reproducible examples), so that you may quicker responses from other people instead of having to waiting for me to answer your question. If you are not sure if it is a bug report or a question, consider using StackOverflow first (I watch StackOverflow questions closely every day). You may also try the [RStudio Community](https://community.rstudio.com). Thanks!
