### ISSUE TITLE
revise doc: markdown shortcode can be used directly

### ISSUE THREAD

**Issue by dongzhuoer** [rstudio/blogdown#249]
in 2.3.3 Shortcode

> To use shortcodes in R Markdown instead of plain Markdown, you have to call the function `blogdown::shortcode()`

Indeed, `<` would be converted to `&lt;`, but `%` seems safe. At least I successfully use the following shortcode ([kakawait/hugo-tranquilpeak-theme](https://github.com/kakawait/hugo-tranquilpeak-theme), I am sorry for not providing an live example, since I 'm not ready to publish it.)

```
{{% alert danger %}}
Here is a danger alert without icon
{{% /alert %}}
```

However, pandoc's markdown rule must still cause some unknown damage. I suggest that you add a footnote to explain this possibility for advanced users (at their own risk).

**Comment by yihui** [comment]
I guess the net gain will be negative in this case: as you said, Pandoc might "damage" the content since it does not recognize Hugo's shortcode. Those who want to risk it anyway should be able to discover it by themselves like you. If I mention this possibility in the blogdown book, some users may complain it doesn't work in certain cases.

On the other hand, personally I don't even recommend using shortcode and I rarely use it myself. It is not standard Markdown, so it is not portable. If you use shortcode, you will be stuck in Hugo and lose the possibility of converting your blog posts to other formats (like PDF). Of course, that is not an issue if you don't need portability.

Thanks for the suggestion!

**Comment by dongzhuoer** [comment]
Well, then I suppose this issue is enough for Google search.

Nevertheless, I want to add an explanation: `%` shortcode ought to be rendered by Hugo's markdown rule. But in blogdown, it's actually rendered by Pandoc's markdown rule. Good news is that, for basic syntax. the result should be identical to what one would expect.
