### ISSUE TITLE
Complicated math expressions not rendered

### ISSUE THREAD

**Issue by dusadrian** [rstudio/blogdown#252]
I am still having difficulties with math expressions in Hugo and blogdown.
It works for simple equations, but more complicated ones are not rendered.

I am trying to achieve this:

$$\prod_{c = 1}^{k} (l_c + 1) = 1 + \sum_{c = 1}^{k}\binom{k}{c}\prod_{s = 1}^{c} l_s$$

It works with individual components such as
$$\prod_{c = 1}^{k} (l_c + 1)$$
or
$$\sum_{c = 1}^{k} \binom{k}{c}$$

but not with
$$\sum_{c = 1}^{k}\binom{k}{c}\prod_{s = 1}^{c} l_s$$
(and neither with the entire equation).

Any hints would be greatly appreciated. Using the latest version of blogdown, and version 0.36 of Hugo.

**Comment by yihui** [comment]
Could you provide a link to the problematic page?

This question is hard to answer because it depends on the MathJax support of the specific theme. I added the support in the default hugo-lithium-theme: https://bookdown.org/yihui/blogdown/output-format.html but there is no guarantee that math works for all Hugo themes.

**Comment by dusadrian** [comment]
Sure, here it is:
https://github.com/dusadrian/academic/blob/master/content/publication/CCubes.md

Thanks again for your answer.

**Comment by yihui** [comment]
So you are using the hugo-academic theme, which is not written by me. You may have better luck with its author @gcushen at https://github.com/gcushen/hugo-academic. Thanks!
