### ISSUE TITLE
install_theme() : Add  theme installation from Gitlab

### ISSUE THREAD

**Issue by petermeissner** [rstudio/blogdown#270]
Using the newest developement version I was hoping to be able to install a theme from Gitlab and not only Github. 

It does not work. 

```
new_site(dir = "docs", theme = "syui/hugo-theme-wave", hostname = "https://gitlab.com/")

## versuche URL 'https://https://gitlab.com//syui/hugo-theme-wave/archive/master.zip'
## Fehler in download.file(url, ..., method = method, extra = extra) : 
##   kann URL 'https://https://gitlab.com//syui/hugo-theme-wave/archive/master.zip' nicht öffnen
## Zusätzlich: Warnmeldung:
## In download.file(url, ..., method = method, extra = extra) :
##  URL 'https://https://gitlab.com//syui/hugo-theme-wave/archive/master.zip': status was 'Couldn't resolve host name'
```

**Comment by gadenbuie** [comment]
`new_site` will add the `https://` and the trailing slash, so you just need to set `hostname = "gitlab.com"`.

The documentation for `hostname` is

> `hostname` Where to find the theme. Defaults to `github.com`; specify if you wish to use an instance of GitHub Enterprise.

I think this could be a little more clear and that maybe `install_theme` can not add the protocol if it exists in `hostname` so that setting `hostname = "https://gitlab.com"` works. I'm going to work up a quick PR to address these.

**Comment by gadenbuie** [comment]
Sorry, @yihui  and @petermeissner, I read the issue too quickly. The issue is that `install_theme` assumes a GitHub style URL for the archive zip, i.e. `https://<hostname>/<user>/<repo>/archive/<branch>.zip`.

GitLab appears to follow `https://gitlab.com/<user>/<repo>/repository/<branch>/archive.zip`.

Bitbucket also has a different URL scheme: `https://bitbucket.org/<user>/<repo>/get/<branch>.zip`

Rather than jump ahead again, here are three options that occur to me:

1. We could add an argument to specify the full URL to the zip file.
2. We could make `hostname` a `match.call()`-like argument with options `github`, `gitlab`, `bitbucket` or accept a third option for GitHub Enterprise hosts that defaults to GitHub URL style.  In this option, we can construct the URL manually in a helper function using the URL templates.
3. Limit `install_theme()` to GitHub-style URLs, make it explicit in the documentation, and provide a link to docs where manual theme installation is described.

Still happy to contribute a PR depending on how you want to go with this :)

**Comment by yihui** [comment]
@gadenbuie Let's do the first option, which was exactly what I said in https://github.com/rstudio/blogdown/issues/264#issuecomment-368281478 a few days ago when @ijlyttle was working on the `hostname` argument. Thanks a lot!

**Comment by gadenbuie** [comment]
@petermeissner I added support for giving `theme` a full url to the repo zip file, and @yihui just merged it. Can you try it? Update to the latest version of blogdown with 
```r
devtools::install_github('rstudio/blogdown')
``` 
and then try the following

```r
new_site(dir = "docs", theme = "https://gitlab.com/syui/hugo-theme-wave/repository/master/archive.zip")
```

**Comment by petermeissner** [comment]
Wow - that was fast ... Works like a charm and is most appreciated.
