### ISSUE TITLE
This will likely get closed as "offtopic" but: GDPR & blogdown

### ISSUE THREAD

**Issue by hrbrmstr** [rstudio/blogdown#299]
It _might_ be handy to have https://discourse.gohugo.io/t/hugo-vs-the-general-data-protection-regulations-gdpr-in-eu-eea/11526 linked somewhere prominently in the repo or as a random package startup message or post-blog-rendering console message to help folks who may be concerned abt GDPR handle GDPR. I can try to figure out some good places for those and issue a PR but didn't want to spin cycles if this would just be rejected as "not an issue for blogdown".

**Comment by yihui** [comment]
Okay, I simply waited for six weeks to make sure this issue is surely the first result when you google for "blogdown GDPR", and I think I can close the issue now. Those who really care about GDPR [should be able to find it.](https://twitter.com/fubits/status/1001183741090435072) Those who don't care probably [don't want to be bothered](https://www.google.com/search?q=GDPR+fatigue).

Thanks for bringing up the issue!
