### ISSUE TITLE
serve_post() possibility?

### ISSUE THREAD

**Issue by pssguy** [rstudio/blogdown#30]
Unless I'm missing something, the only way to view output of an individual post is via serve_site() which previews the whole site

This could get a bit time-wasting as the blog expands and only one post is being worked on

**Comment by yihui** [comment]
This is on my plan. Thanks for casting another vote!

**Comment by yihui** [comment]
It should not be too slow now due to the caching mechanism: https://bookdown.org/yihui/blogdown/local-preview.html My website has about 700 posts, and Hugo can render the whole site in about one second.

**Comment by pssguy** [comment]
So should this be working on v 0.0.33?

This is what happens on the second time of running `serve_site() in case that made any caching difference
```
> blogdown:::serve_site()
```
There is about a minute wait before anything else shows in console (in a previous version 0.0.25 it showed libraries being loaded as though some/all of the .rmd files were being re-run)

```
Started building sites ...
Built site for language en:
Built site for language en:
3 of 3 drafts rendered
0 future content
0 expired content
31 regular pages created
25 other pages created
104 non-page files copied
135 paginator pages created
10 tags created
10 categories created
total in 12474 ms
Serving the directory C:\Users\Andrew\Documents\R\mainWebSite at http://127.0.0.1:4321/replace-this-with-your-hugo-site.com/
```
So that took another 12+ seconds. There is then a further delay before the site appears in the viewer 
Total time is just under 2 minutes
I have not tried build_site() on 0.0.33. That took longer than serve_site() as I recall

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10    bookdown_0.3.19 digest_0.6.12   rprojroot_1.2   mime_0.5        backports_1.0.5
 [7] magrittr_1.5    evaluate_0.10   blogdown_0.0.33 stringi_1.1.5   rmarkdown_1.5   tools_3.4.0    
[13] servr_0.5.6     stringr_1.2.0   httpuv_1.3.3    yaml_2.1.14     compiler_3.4.0  htmltools_0.3.6
[19] knitr_1.15.20  
```

**Comment by yihui** [comment]
Okay, there is nothing I can do for the 12 seconds. This build time is beyond my control. I think it is this slow probably because (1) your hardware is not fast enough; (2) your theme is complicated; and/or (3) Windows...

That said, there is one thing I can help with, which is the delay before you see the website in the viewer. Try a daily version of RStudio first; if it is still slow, you can set `options(blogdown.publishDir = '../my-public')` (feel free to use other dir names) so that the publish dir is generated outside of the RStudio project. The delay was caused by the large number of file changes in the `public/` dir in the project, and RStudio may be busy tracking the status of these files.

**Comment by yihui** [comment]
Another option is you just compile the single Rmd to HTML while you work on it. Yet another option is to use the Rmd notebook mode. Of course, you don't know what the post looks like on the website until you build the site.
