### ISSUE TITLE
 title with semi colon blocks everything

### ISSUE THREAD

**Issue by jcolomb** [rstudio/blogdown#310]
if the title of a blog has a semi colon, the serve_site() will not work and the site cannot be build anymore.

It can be difficult to spot (it was for me), because as long as the public folder is not erased, other changes are still made (no new blog posts will be added though, even newer one who do not have the problem).

It would be great if blogdown:::new_post_addin() would either give an error when the title has semi-colon or put the title between quotes as a default behavior.

thanks

**Comment by yihui** [comment]
Please always, always provide [a minimal, self-contained, and reproducible example](https://yihui.name/en/2017/09/the-minimal-reprex-paradox/) when reporting issues.

The semi-colon `;` is not a special character in YAML, and there is no need to quote the title unless it contains _other special characters_. Without a reprex, it is hard to know what you are talking about exactly, and I'll have to guess blindly (maybe you mean colon instead of semi-colon?). I tried a semi-colon in a title, and the page could be built successfully.

If you use the "New Post" addin, the title should be automatically quoted if it contains special characters. If you need to edit the title, you can use the "Update Metadata" addin: https://bookdown.org/yihui/blogdown/rstudio-ide.html

**Comment by jcolomb** [comment]
Dear Yihui, please forgive me. I spent 2 hours finding why my website was broken and did not take the time to test what happened for real, and confused semi-colons and colons...

Indeed, it was a colon ":", and I added it manually after using the new_post_addin() function.

I wonder if it (new_post_addin() function) should not add quotes per default and not only when there is a special character. Would it be more standardised?

Sorry again.

**Comment by yihui** [comment]
No worries. Next time please do not spend two hours on such problems. Feel free to ask a question with a reproducible example after you spend more than 10 minutes and still cannot figure it out. I'll be happy to save you two hours. I just don't want to blindly guess.

FWIW, YAML is a pretty bad language in my eyes. You are not the first person who have been confused: https://twitter.com/xieyihui/status/956741818527428608

**Comment by yihui** [comment]
I just tested it, and there will be error messages in the R console if your title contains colons. If you don't see the errors, you may try the preview version of RStudio: https://www.rstudio.com/products/rstudio/download/preview/
