### ISSUE TITLE
No images or charts visible on website

### ISSUE THREAD

**Issue by visuelledata** [rstudio/blogdown#320]
No charts or images are being published on my site when I blogdown::build_site() > Push. I'm not entirely sure why this is happening, but I've tried every solution I can find on Stack Overflow and google.  
  
  
- [Here is my site's GitHub repo.](https://github.com/visuelledata/website)  
- This is my site: http://visuelledata.netlify.com/ 
- Theme: ghostwriter 
- blogdown::hugo_version() returns '0.20'
- Using blogdown version 0.8

This issue is only occurring with my 2 most recent blog entries, so I assume that this an issue caused by an update to blogdown, my theme, or a combination of things.

**Comment by gadenbuie** [comment]
It's probably because you ignore all files in the `static` folder: https://github.com/visuelledata/website/blob/master/static/.gitignore

Blogdown writes out plots to subfolders of `static` and you should include those files in your repo. See https://bookdown.org/yihui/blogdown/static-files.html for more info about how the `static` folder works.

My guess is that you ran `knitr::knit()` directly on the other posts before, which then saved the plot images inside `content/post` which is how they ended up showing up in your final website.

**Comment by yihui** [comment]
I think @gadenbuie is correct. You seem to have run into the same issue as @DataStrategist: https://github.com/rstudio/blogdown/issues/169#issuecomment-404570353

**Comment by visuelledata** [comment]
Thanks everyone, got it working!
