### ISSUE TITLE
Broken links in RSS feed

### ISSUE THREAD

**Issue by cfhammill** [rstudio/blogdown#337]
When the baseurl of a project is a subdirectory, blogdown can fail to generate the correct image links in the RSS feed. This applies to figures generated by code chunks. 

Steps to reproduce:

## Start a new project 
```r
blogdown::new_site(serve = FALSE)
```

## Edit config.toml

```
baseurl = "https://example.github.io/blog"
```

## Enable full content xml feeds 

Add the hugo embedded [rss.xml](https://gohugo.io/templates/rss/#the-embedded-rss-xml) to layouts/rss.xml then edit L22 to

```
 <description>{{ .Content | html }}</description>
```

## Serve the site

```r
blogdown::serve_site()
```

## View the results 

Navigate to:

http://127.0.0.1:4321/blog/2015/07/23/hello-r-markdown/  (or whichever port you use)

to see the figure generated properly. 

Then navigate to:

http://127.0.0.1:4321/blog/index.xml

and observe that the figure isn't in the full content xml. In the html output approx L102

/blog/blogpost/2015-07-23-r-rmarkdown_files/figure-html/pie-1.png 

does not exist. The redundant /blog comes from the baseurl.

**Comment by yihui** [comment]
First of all, I appreciate the steps, but please read this next time to help me help you more quickly: https://yihui.name/en/2018/06/copy-and-run/

Second, in most cases, the baseURL should have a trailing slash, i.e., `baseURL = "https://example.github.io/blog/"`. The trailing slash is important.

Third, this appears to be an obvious bug of Hugo in my opinion: `.Content | html` should not turn `/blog/foo.png` to `/blog/blog/foo.png` in your case. I don't have time to report it to Hugo (please feel free to do it if you have time).

Fourth, I recommend that you either [consider Netlify instead of Github Pages](https://yihui.name/en/2017/11/301-redirect/) or use the [RSS content module](https://developer.mozilla.org/en-US/docs/Web/RSS/Article/Why_RSS_Content_Module_is_Popular_-_Including_HTML_Contents). Both should easily solve your problem. Hacking the HTML pages should be the last resort. If you use Netlify, you can add a simple 301 redirect rule to redirect `/blog/blog/` to `/blog/`. If you use the RSS content module, replace

```xml
<description>{{ .Content | html }}</description>
```

with

```xml
<content:encoded>{{ "<![CDATA[" | safeHTML }}
  {{ .Content }}]]>
</content:encoded>
```

Here is the kind of "minimal reprex" I was expecting: [test-rss.zip](https://github.com/rstudio/blogdown/files/2435263/test-rss.zip). Thanks!

**Comment by cfhammill** [comment]
Thanks Yihui,

1. Good point, I hadn't thought of zipping it all up and attaching, sorry.
2. I have the trailing slash in my actual blog, so that shouldn't factor in to this bug.
3. Yes it does seem like a hugo bug, I'm happy to report.
4. I'm hesitant to migrate hosting, but the RSS content module seems like just the right thing.

Thanks again!

**Comment by yihui** [comment]
You are welcome!

**Comment by cfhammill** [comment]
For anyone else who get bitten before hugo gets fixed, the `CDATA` trick fixed my problem. I used

`<description>` instead of `<content:encoded>`, but otherwise exactly as @yihui suggested.

```
<description>{{ .Content | html }}</description>
``` 

became

```
<description>{{ "<![CDATA[" | safeHTML }}
  {{ .Content }}]]>
</description>
```
