### ISSUE TITLE
Links to figures are not correct in RSS

### ISSUE THREAD

**Issue by hturner** [rstudio/blogdown#34]
When blogdown processes the `.Rmd` files it creates `.html` files in the `blogdown` directory with `<img>` tags such as

    <img src="#####../content/blog/2017/01/13/mapping-users/mapping-users_files/figure-html/unnamed-chunk-2-1.png" width="672" style="display: block; margin: auto;" />

In the published `.html ` the URLs end up as relative links, e.g. `src="figures/unnamed-chunk-2-1.png` which works fine. However the temporary links remain in the RSS generated by Hugo, so the images aren't found in the `.xml` file.

For now we're getting round this by [post-processing the `.xml` file](https://github.com/forwards/website_source#publishing-the-website).

**Comment by yihui** [comment]
There is no documentation yet, but this is a solved problem. To publish a website, you need `blogdown::build_site()`, and the .xml files will be post-processed.

**Comment by hturner** [comment]
Thanks, I see that now. One thing it would be useful to have in the documentation is it's important to stop any daemonized server first (via `servr::daemon_stop()`) - I've got used to having the website served locally in the background and then running `build_site(local = FALSE)` still seems to build as if `local = TRUE`.

Unfortunately I still have an issue though, when using `build_site()` the links are missing a "/", e.g. I get `http://forwards.github.io/blog/2017/01/13/mapping-usersfigures/unnamed-chunk-2-1.png` where I should have `http://forwards.github.io/blog/2017/01/13/mapping-users/figures/unnamed-chunk-2-1.png` so the links are still broken.

**Comment by weiqiwang15** [comment]
I encountered the same problem with displaying images in username.github.io. It seems that the problem still exists up to now.

**Comment by yihui** [comment]
@hturner That is a good suggestion for the documentation, and actually I guess I can provide a fix to avoid rebuilding the site after you run `build_site()`. I'll fix the missing slash issue, too.

@weiqiwang15 Do you have an example on Github? I saw your repo https://github.com/weiqiwang15/weiqiwang15.github.io but it does not appear to be a Hugo website (looks like Jekyll instead); blogdown only supports Hugo at the moment. To create a new website, please follow the instructions in README: https://github.com/rstudio/blogdown

**Comment by weiqiwang15** [comment]
Thank you for your reply. I couldn't resolve the problem so I switched back to the Jekyll solution. I'll create a new repo and try to replicate the problem. Thanks.

**Comment by wangweiqi15** [comment]
I used two repos (**blog_source** and **wangweiqi15.github.io**) to store the files as you suggested in this [post](https://proquestionasker.github.io/blog/Making_Site/).

I have little experience with html so I'm not sure if the screenshots below are where the problem lies. Hopefully it can give you some clue. Thanks.

---

In **`blog_source/blogdown/post/2015-07-23-r-rmarkdown.html`**

![screenshot from 2017-01-25 10-53-55](https://cloud.githubusercontent.com/assets/25342670/22288260/066d088e-e2ee-11e6-82f2-6d29895b99d5.png)

---

In **`wangweiqi15.github.io/2015/07/23/hello-r-markdown/index.html`**

![screenshot from 2017-01-25 11-05-11](https://cloud.githubusercontent.com/assets/25342670/22288306/3c84a5f8-e2ee-11e6-9587-d2b2d9f04559.png)

---

Figure in blog post can't display correctly.
![screenshot from 2017-01-25 10-46-51](https://cloud.githubusercontent.com/assets/25342670/22287810/24f5ba96-e2ec-11e6-80ac-a6bbb811718c.png)

**Comment by yihui** [comment]
@hturner The missing slash was due to your configuration, and I just submitted a PR to fix it https://github.com/forwards/website_source/issues/1

@wangweiqi15 Your issue has been fixed. Please reinstall **blogdown**:

```r
devtools::install_github('rstudio/blogdown')
```

**Comment by wangweiqi15** [comment]
Working like a charm now! Thank you!!

**Comment by hturner** [comment]
Ah, so simple! Thanks very much!
