### ISSUE TITLE
Support initializing a new_post() with a page bundle

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/blogdown#351]
Hi @yihui, after looking through [Romain's question](https://twitter.com/dvaughan32/status/1076857852856332288) on Twitter, I found that [page bundles](https://gohugo.io/content-management/page-bundles/) solve the issue of keeping images and data files separate from the post that they go with. It also plays nicely with RStudio's built in autocomplete and image preview feature, as demonstrated on twitter.

I tried my hand at creating a simple blog using page bundles, which worked nicely here
https://github.com/DavisVaughan/leafblog

After seeing how well it worked, I converted my site to use them. I'm very happy with the result.
https://github.com/DavisVaughan/data-insights/tree/master/content/post

Would it be possible to give `new_post()` a way to init a post with a page bundle setup? It would:

- Create a folder under `post/` with the name that normally is given to the `md`/`Rmd`.
- Create an `index.md` / `index.Rmd` inside that folder

That would be a great resource, at least to me as I try and switch over to using this setup.

The only thing I have had to change after using this setup is the fact that links now look like `base_url/post/2018-01-01-folder-name/slug` which I fixed by setting the `[permalinks]` config parameter to use `post = "/:year/:month/:day/:slug/"`. If users want the exact default behavior, then I think they can use `post = "/post/:slug/"`

**Comment by yihui** [comment]
Done. Set `options(blogdown.new_bundle = TRUE)` in your `.Rprofile`, and new posts will created as bundles. Thanks for the great suggestion and pointers!

**Comment by apreshill** [comment]
Just realized I posted this as a comment on the commit rather than in this thread-

https://github.com/rstudio/blogdown/commit/ac3b2bb3b4444457f531888a4b49d6a89764bc33#commitcomment-32396621

Here is the text:

Just diving in to use this option, and am noticing an issue with links. If you use this option, the default Addin behavior is to populate the post "slug" for you- you cannot *NOT* have a post slug. The issue is is that if you *do* use a slug on a bundled post, what populates into your public directory is this:

```
public/
  |- 2019-02-20-slug
      |- slug
          |- index.html
```

This means that links to your bundled posts (if there is a slug) will look ugly :sad:

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/hugo-netlify-toml/

And this link will not work:

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/

But in my local version, if I remove the slug, I can access my post as I want:

https://alison.rbind.io/post/2019-02-19-hugo-netlify-toml/

So I am wondering if the default behavior of the Addin can be changed so that when you have the page bundle option turned on, the slug is deactivated somehow so the user cannot set it?
