### ISSUE TITLE
build_site throws errors when there is a data directory

### ISSUE THREAD

**Issue by jbryer** [rstudio/blogdown#356]
I recently updated blogdown and it seems to be processing files in the data directory. Why? When I build_site at this repo many errors are thrown: https://github.com/jbryer/DATA606Fall2018

**Comment by yihui** [comment]
**blogdown** does not do anything to the `data` directory. It must be Hugo. You may have updated Hugo (from a very old version to a recent version). Since a certain version of Hugo, it only supports YAML/TOML/JSON data under the `data` directory (no `.csv` or `.rda`), so you have to put other types of data in other directories. Two choices:

1. Downgrade Hugo;

2. or move those unsupported data files to other directories. You may be interested in #351.

Anyway, the `data` directory is for Hugo only.
