### ISSUE TITLE
RStudio quits when running blogdown::serve_site()

### ISSUE THREAD

**Issue by zenggyu** [rstudio/blogdown#366]
operating system: ubuntu 18.04
rstudio version: v1.1.463
blogdown version: v0.10
hugo version: v0.54.0
hugo-academic version: v3.3.1

Steps to reproduce the problem:

1. Open RStudio.
2. Create a new project.
3. Run `blogdown::new_site(theme = 'gcushen/hugo-academic')`.
4. Run `blogdown::serve_site()`.

RStudio quits suddenly after running the last command. However, if I open R in a terminal and execute the `blogdown::serve_site()`, a browser will pop up and everything seems fine.

**Comment by yihui** [comment]
You didn't follow the issue guide to provide your session info. I have no idea about the versions of your R packages or R itself. If you haven't updated all your R packages, please do. Otherwise you may try the preview version of RStudio: https://www.rstudio.com/products/rstudio/download/preview/

FWIW, I tested it with R 3.5.2 and the latest versions of all packages under Ubuntu 18.04, and was unable to reproduce your issue.
