### ISSUE TITLE
Unused argument in blogdown::new_post()

### ISSUE THREAD

**Issue by fananan** [rstudio/blogdown#379]
hey, did anyone come across same issue as i did when creating a new Rmarkdown post? 
The error i got when i typed `blogdown::new_post(rmd=TRUE) is > blogdown::new_post(rmd = TRUE) Error in blogdown::new_post(rmd = TRUE) : unused argument (rmd = TRUE)`
I tried to google but couldn't find the answer. i know the other way to create Rmarkdown post rather than markdown is to use New Post addins. but i'd like to know the reason i got this error.  

Thank you in advance!

**Comment by tcgriffith** [comment]
that's because there's no rmd argument in function new_post()

**Comment by yihui** [comment]
Where did you learn `blogdown::new_post(rmd=TRUE)`? We need to correct it if we know the misleading source.

**Comment by cderv** [comment]
In fact this is all due to an old change https://github.com/rstudio/blogdown/commit/9f8f9e03491090d1dfaf2571cecc6eefcbcc29fa where the `rmd` argument existing at the time was renamed `ext`. 

Some blog post from that time (before 10/2017) are referencing the `rmd` argument. Among them, the demo blogdown website itself 
* https://blogdown-demo.rbind.io/2017/10/06/adding-r-code-to-r-markdown-posts/
but also others 
* https://sia.planning.unc.edu/post/using-blogdown/
* https://apreshill.rbind.io/post/up-and-running-with-blogdown/

and surely other we may found from that time.

Also, I don't see anything about this argument name change in the NEWS file. Could be add something retroactively ? 

@yihui, I will PR some updates where I can for the post. A proposition : what do you thing of adding a check in arguments from `new_post` in case `rmd` is provided to say that it is Deprecated and one should use `ext` instead ? I can work on that if you want.

**Comment by yihui** [comment]
@cderv I think this argument only existed before the first CRAN release of this package, so this change didn't appear in NEWS.

**Comment by fananan** [comment]
Thank you for all your responses! I learned this argument from these two blogs:
https://alison.rbind.io/post/up-and-running-with-blogdown/
and
https://knausb.github.io/2017/06/a-first-post-using-blogdown/

**Comment by fananan** [comment]
I tried using `ext` as following: `blogdown::new_post("test", ext = getOption("blogdown.ext", ".Rmd")) ` and it worked :)

**Comment by knausb** [comment]
I've updated 

[https://knausb.github.io/2017/06/a-first-post-using-blogdown/](https://knausb.github.io/2017/06/a-first-post-using-blogdown/)

to reflect the proposed change. Thanks for bringing this to my attention!
