### ISSUE TITLE
I can only commit all the files from Yihui theme but not other hugo themes 

### ISSUE THREAD

**Issue by seymakalay** [rstudio/blogdown#388]
[---](url)

By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.name/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.
`[](url)`

**Comment by cderv** [comment]
Hi, 

You did not fill the issue template and you did not provide enough information so that we can help you. 

From the title, it seems like a git workflow issue and more like a question than a bug report. I think you should asked on Stackoverflow or community.rstudio.com. There is a broad community of Rusers there. 
You can also look into blogdown website repo to find examples on how people are dealing with theme and git.

Hope it helps

**Comment by yihui** [comment]
You didn't follow the issue guide. For example, you cross-posted it at https://stackoverflow.com/q/56518713/559676 but didn't mention it here (as required by the issue guide). Anyway, the question is unclear to me, and I don't know how to answer it.
