### ISSUE TITLE
Feature request: Using `output` option within blogdown posts.

### ISSUE THREAD

**Issue by jooyoungseo** [rstudio/blogdown#420]
It would be so much nicer if we could use `output` option in blogdown posts' YAML.

For example, I have been using `academic` theme, and sometimes I would like to utilize `distill::distill_article` output format for a specific post.

Do you think it could be achieved?

**Comment by tcgriffith** [comment]
You can drop the post under `static/` and link to it. so that the CSS styles of the blogdown theme will not interfere with the Rmarkdown styles. This way, the Rmarkdown document will be served "as is" by hugo/blogdown.

But nice features such as taxonomy(tags, categories etc) will be missing.

Another idea is to embed the rmarkdown into the blogdown post, I don't know if that's possible.

**Comment by cderv** [comment]
> It would be so much nicer if we could use output option in blogdown posts' YAML.

About this, from the blogdown book about _output format_, I think you can already specify a output format by post. See https://bookdown.org/yihui/blogdown/output-format.html#output-format

Did you already try that to see what it renders too ? 

There indeed may be conflict in style and other web elements. That is why blogdown use already a special template to render `html_document2` output format. You may need to do the same and work on the template to only keep what can be rendered through Hugo.

There was a method to provide `base_format` to `html_page` but I don't know how it would work for distill which is a rather advanced format. See this [community question](https://community.rstudio.com/t/use-custom-output-format-in-blogdown/24795/4)

It is possible Hugo and Distill not work well together. 

@tcgriffith advices are the one to follow to include external web pages into your hugo website. 
Here a hugo discussion about it https://discourse.gohugo.io/t/what-is-a-better-way-to-include-a-full-external-html-page-and-its-resources-into-blog/9287

**Comment by yihui** [comment]
I'm afraid it won't be easy to use the Distill style with Hugo/blogdown. The style involves special CSS stylesheets and JS libraries. I feel these dependencies are complicated enough, not to mention that the Academic theme itself also has a lot of dependencies. I doubt these things could work nicely together.

A Hugo theme of the Distill style has been on my plan for a long time, but I still don't have time to develop it (perhaps I'll have a little more freedom in March next year). I feel its CSS can be greatly simplified to make it more lightweight and portable, therefore you can have both Hugo/blogdown and Distill (currently you can only choose one).

**Comment by yihui** [comment]
I'm closing this issue since it's beyond the scope of **blogdown**, and is more like a Hugo theme issue.

> A Hugo theme of the Distill style has been on my plan for a long time

I meant https://prose.yihui.org but I only briefly worked on it for about two weeks and was interrupted. I'll see if I could catch up later this year.

BTW, since Quarto has come, and it has included a lot of distill features, it may fulfill the original request, too.
