### ISSUE TITLE
Blogdown + Hugo (academic) + Medium 

### ISSUE THREAD

**Issue by data-datum** [rstudio/blogdown#423]
I would like to know how to have a widget to share my Medium posts in blogdown. I have this code 

`<div id="medium-widget"></div>
    <script src="https://medium-widget.pixelpoint.io/widget.js"></script>
    <script>MediumWidget.Init({renderTo: '#medium-widget', params: {"resource":"https://medium.com/@data_datum","postsPerLine":1,"limit":4,"picture":"small","fields":["description","author","claps","publishAt"],"ratio":"square"}})</script>`

but I do not know how to share this in my personal profile with blogdown

**Comment by tcgriffith** [comment]
Easy:

- Create a custom template file `layouts/partials/widget_medium.html`
- Put `{{ partial "widget_medium.html" . }}` into the template file where you want it to appear. For example, `layouts/_default/single.html` is for post, etc.

Try it out, if you can't get it to work, then bring your repo back here.

**Comment by data-datum** [comment]
I was not ablet to do it. Here is my repo https://github.com/data-datum/rnv-cv

**Comment by tcgriffith** [comment]
Well, the Academic theme is much complicated than I thought, so my PR above took another path.

 In summary:

- Create a shortcode (instead of a partial template)
- Use the shortcode in the posts.md

I Tested and worked on my local machine, please have a look.

Also, don't forget to delete the `layouts/partials/widget_medium.html` under your `content/` directory
