### ISSUE TITLE
R output not fully showned on the website

### ISSUE THREAD

**Issue by Jansonboss** [rstudio/blogdown#427]
After I rendered the R markdown file and put it into the website, the output for some reasons just doesn't show up fully. Can anyone help with this?

![question1](https://user-images.githubusercontent.com/40192895/71830807-6520e300-305c-11ea-83c0-20560731ab7d.PNG)

**Comment by cderv** [comment]
Hello, 

It seems you skipped the issue template. You can find it [here](https://github.com/rstudio/blogdown/blob/master/.github/ISSUE_TEMPLATE.md)

You current issue is more a question than a bug report. You should ask such questions in https::community.rstudio.com or Stack overflow. There is a broader community of people there ready to help. 

Also, the issue template asked for a reproducible example because it helps us help you. Currently, only with a screenshot, it difficult to know what happened. It seems that a loading issue in your browser. 🤔 If you can provide some more information following the [issue guide](https://yihui.name/issue/), it would really help. 

Thank you

**Comment by Jansonboss** [comment]
Thank you for your reply and sorry about the issue template! I am quite new to this place.

Just like what you said, this is the problem of browser. There is an issue for the r output shown on the google chrome, but everything is fun when I switched to Microsoft edge.
