### ISSUE TITLE
Format table in Rmarkdown

### ISSUE THREAD

**Issue by TrungLeVn** [rstudio/blogdown#428]
Hi,
I am trying to add a table to my post to the Hugo Academic themes using Rmarkdown with the kableExtra package in an R chunk code. However, it seems that I can not customize the styling options to my table such as to position the table to the center of the page or to use the "basic" format in the bootstrap options (by default, the table appears with strips of alternative colors in each row).

Here is the reproducible code:
```{r, echo=FALSE,error=FALSE,message=FALSE}
library(kableExtra)
library(knitr)
library(dplyr)
options(knitr.kable.NA = '')
options(kableExtra.html.bsTable = TRUE)
dt = mtcars[1:10,1:3]
kable(dt,format = "html") %>% kable_styling(position = "right",bootstrap_options = "basic")
```

**Comment by jemus42** [comment]
Hugo Academic doesn't seem include bootstrap (I only checked by quickly cmd+F'ing through the source of https://themes.gohugo.io/theme/academic/), so my guess is that that's why bootstrap options don't work, as `kable` only adds the appropriate CSS classes to the table output, but doesn't forcibly include bootstrap (which would be a rather huge dependency, purely for some table styling)

You would have to manually add table-related CSS to your theme I think.
