### ISSUE TITLE
Support to build a single-page

### ISSUE THREAD

**Issue by andremrsantos** [rstudio/blogdown#459]
Hi,

I recently have been using blogdown to track and share some of my analyses locally with great success. But in my daily use, I found more than one time wishing to build a single Rmd page and I was wondering if is that a feature available or that you are looking forward or if there is a workaround it?

Thanks for everything

Best

**Comment by yihui** [comment]
If it is only a single Rmd, why not render it to HTML directly? You can either click the Knit button in RStudio or call `rmarkdown::render()`. I don't see the need for **blogdown** in this case.

**Comment by yihui** [comment]
If the Rmd file has to be inside a **blogdown** project, you may consider putting it under the `static/` directory and call `build_dir()` in the script `R/build.R`: https://bookdown.org/yihui/blogdown/static-files.html

**Comment by Athanasiamo** [comment]
I'd actually also really love this feature. I see your points above, but I think there are cases where building a single page would be beneficial, without resorting to `static/`. 

I think its good to keep all content in `content/` for clarity. In my case, I'd love to have a GH action re-build my about page on crontab, to update some web-resources (the Rmd grabs google scholar information about papers and citations, and I'd love those to be updated regularly). But currently, getting it to knit decently without causing yaml to disappear in the  `md` (all my other content is in md (`blogdown.method = "markdown"`) , or resorting to html for a single content page. I've not been able to get a `rmarkdown::render` command on this file to actually produce what I'd like.

**Comment by cderv** [comment]
Hello @Athanasiamo, 

do you have an example blog to link to ? It would help see further what are the limitations.
And is your about page the same format as others post in the website ?
 
I asked that because I really think with new **blogdown** v1+ this is possible to render a single Rmd in the site. 

First, let's recall that by default Rmd **are not rebuilt anymore** unless knitted by the user or ask to be re-render by the user using `build_rmd` argument in `build_site`. New behavior is mentioned in : https://blog.rstudio.com/2021/01/18/blogdown-v1.0/#workflows

I see several solutions to your use case based on the value `build_rmd` can take.

`build_rmd` can take a logical value and will rebuild everything if TRUE. This is not what you want.

But you can get more control as it can take a function - either a built in function and a character alias can be used, but you can also pass a custom function that return a character vector of file to rebuild. For example, you can make use a build in function to trigger a rebuild like `newfile` : Your GH action would remove the `about/index.md` and `build_site(build_rmd = "newfile")` would see that output file is missing and rebuild the associated Rmd `about/index.Rmd`. 
You could also create a custom function to suit the workflow you need - the function just need to return the file path to rebuild.

At last, you can also directly pass a character vector of Rmd filepaths to rebuild. For example, the path to your about page. This means you can call something like this: 
```r
blogdown::build_site(local = FALSE, run_hugo = FALSE, build_rmd = "content/about/index.Rmd")
```
to only build the rmd file, for production mode without running hugo (because you would build the site later, but you can set to TRUE here too). This will rebuld the Rmd in the context of the blogdown project. (which is a bit different than `rmarkdown::render()`)

Does this help ? Did you already try this new workflow ? Do you think it would work for you ?

**Comment by Athanasiamo** [comment]
hi!

Thanks for being quick. I had had a look at that function but had not really understood all its capabilities! Thank you for the clarifications. 
Indeed your last bit of code there did the trick. 

For some reason, in the GH action it was also rendering another Rmd that will not knit (it wont locally either anymore) which it does not try to do locally (it has a companion md already), so I had to specifically ask it to build the file I wanted, so it would ignore the other one. This behaviour happened both on the CRAN and remotes github install of blogdown, so not sure what is happening there. 

But my "problem" is solved and I am very satisfied! Thank you!

**Comment by cderv** [comment]
Thanks for letting us know your experience with this. I think the new `blogdown::build_site()` could benefit more documentation maybe in a special vignette / articles about Workflow with **blogdown**. 

> For some reason, in the GH action it was also rendering another Rmd that will not knit (it wont locally either anymore) which it does not try to do locally (it has a companion md already), so I had to specifically ask it to build the file I wanted, so it would ignore the other one. This behaviour happened both on the CRAN and remotes github install of blogdown, so not sure what is happening there.

Sorry I don't completely understand: What command was not working ? And which one is working ? 
if you think there is something off (but don't know why) do not hesitate to open an issue and we'll look into.

**Comment by Athanasiamo** [comment]
sorry for being unclear!

`build_site(build_rmd = "newfile")` was failing because it was trying to render a file it should not have. There's an Rmd in my content that will not knit on a CI because of interactivity issues (using the rorcid pkg), so I really dont want blogdown to try to knit it on GHA. And that specific Rmd does already have a companion `md` so I dont know why the command was trying to render it also, something it locally was not attempting. So I dont know exactly what was happening there.

Thankfully, in my case I have a very specific file I wanted rendered, so using `blogdown::build_site(local = FALSE, run_hugo = FALSE, build_rmd = "content/about/index.Rmd")` solved my issue, specifically rendering the exact file I wanted re-knit :) Awesome sauce!
