### ISSUE TITLE
Deploying website

### ISSUE THREAD

**Issue by andrewdarmond** [rstudio/blogdown#471]
I have a github. I have a netlify account. I have my website build in blogdown. I don't know to connect all them. I have uploaded things in GitHub prior to this so how do I make a repo that allows me to fit the file. Or do i make it on netlify? I am lost. Please help! The site is almost done but I wanted to do the launching execution first so I can understand the updating ability too.

**Comment by tcgriffith** [comment]
Basically you 1. make the website repo 2. upload to github 3. connect it on netlify.
Detailed steps are documented in the blogdown book 3.1, please check them out.
https://bookdown.org/yihui/blogdown/netlify.html

Note that the repo issues is mostly for reporting bugs, closing

**Comment by andrewdarmond** [comment]
So I'm trying really hard to upload to GitHub but its not working

**Comment by yihui** [comment]
You didn't follow the issue guide (which you deleted but were asked not to) to mention that you were cross-posting: https://stackoverflow.com/q/63407171/559676

Could you read and follow [the issue guide](new) exactly to provide all the required information? As requested, please do not ignore or delete the issue guide in your post, otherwise it is usually hard for us to help you. Thanks!
