### ISSUE TITLE
Netlify & Post-production R script

### ISSUE THREAD

**Issue by giabaio** [rstudio/blogdown#489]
Hi all,
I hope this will make some sense! :-)
So: I have a site in `blogdown`, which I then deploy in `Netlify` [https://stats-he.netlify.app/](https://stats-he.netlify.app/). All works like a charm. However, I have written an `R` script to post-process the build to modify some text in the `public/` folder. For instance, I would like to format the name of the authors who are members of our group in the `publications` section as 
> **A Name**

instead of what` hugo`/`wowchemy` do by default, which is
> **Another Name**
(so full first name, rather than just the initial). 

My `R` script works perfectly (and it's actually fairly simple --- just some basic `gsub`). If I run the script post `blogdown::serve_site()` and then upload the whole `public/` folder on a server to which I have access, the [result](https://egon.stats.ucl.ac.uk/research/statistics-health-economics/) is as desired. However, when I deploy through GitHub and then `Netlify`, the process is not "complete" as the post-build script is not run.

Is there any obvious/easy way to make this happen through to `Netlfiy`?

My apologies if this is trivial and/or I've missed something obvious!
Thanks
Gianluca

**Comment by yihui** [comment]
In that case, you have to commit and push the `public/` folder to your Github repo, and let Netlify just deploy that folder, **without building the site again with Hugo**. On app.netlify.com, leave the `Build command` empty, and set the `Publish directory` to `public` like this:

![image](https://user-images.githubusercontent.com/163582/95519790-74d2ac80-098b-11eb-85d3-47823e6ca7aa.png)

That's because you don't R on Netlify, and there is no way you could post-process the `public` folder using R. If you prefer building the site with Hugo on Netlify and post-process the `public` folder, you'll have to use other tools available on Netlify (such as shell scripts).

**Comment by giabaio** [comment]
Thank you @yihui! that is very helpful --- I thought it had to do with passing directly the processed `public/` folder. I'll explore the shell scripts too, though and, if helpful for other people, I can come back and post extra stuff (provided I find something sensible...).

Thanks!

**Comment by tcgriffith** [comment]
Maybe a hugo solution is better than an R script?

If you are familiar with hugo, you can use a json list to store authors' info like full-name, short name, then display them as needed.

example: 

author data: https://github.com/cosname/cosx.org/blob/master/data/members.yaml

some custom hugo template: https://github.com/cosname/cosx.org/blob/master/layouts/partials/author.html

more on hugo data templates: https://gohugo.io/templates/data-templates/

**Comment by giabaio** [comment]
Thank you @tcgriffith ! That's very helpful. And agreed that to keep all within the Hugo machinery *is* more efficient --- it's just that I know my way around `R` a lot better than I do around Hugo... ;-)

I'll check these out though --- many thanks!
