### ISSUE TITLE
Encode `index_files` as full-path

### ISSUE THREAD

**Issue by andremrsantos** [rstudio/blogdown#501]
Hi,

I've been using blogdown on a personal lab notebook and notice after v.0.21 update that my main page, which includes the most recent post in full, the figures within `index_files` were not rendering. By checking their paths, I noticed they are relative to the post page.
A quick improvement is to fix these files path using `encode_paths` which right now just skips when detect `index_files` paths.

This improvement would be greatly appreciated. Thanks for everything and great job everyone!

---
By filing an issue to this repo, I promise that

- [ ] I have fully read the issue guide at https://yihui.org/issue/.
- [ ] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [ ] I have learned the Github Markdown syntax, and formatted my issue correctly.

**Comment by cderv** [comment]
Thanks for the feedback. 

Is all this happening when working on a new post ? Or is it happening for old posts ? 
I would guess the former.

> were not rendering.

is it in preview mode or in the build website ? 

> I noticed they are relative to the post page.

I believe this is due to the new default support for leaf bundle in 0.21. See the [NEWS ](https://github.com/rstudio/blogdown/blob/master/NEWS.md#changes-in-blogdown-version-021)
The piece of code you mentioned 
> encode_paths which right now just skips when detect index_files paths
was added specifically to support leaf bundle mode in hugo.

I believe this is related to #499 

you can try set `options(blogdown.new_bundle = FALSE)` to have the old behavior for now.

**Comment by yihui** [comment]
I think the problem here is, the Hugo theme displays the full content of a post on the home page, and images in the post won't be found because their paths are relative to the post instead of the home page. I can fix this issue in **blogdown**, but I'll do some research to see if there is a solution in Hugo first, because my fix would introduce another issue.

**Comment by yihui** [comment]
Please the development version via

```r
remotes::install_github('rstudio/blogdown')
```

Note that you need to recompile the old post once.

Thanks for the report!

**Comment by yihui** [comment]
FYI I just pushed an alternative fix to this problem, which should be more robust:


```r
remotes::install_github('rstudio/blogdown')
```
