### ISSUE TITLE
RMD post cannot present image rendered with R code in theme starter-academic

### ISSUE THREAD

**Issue by anhhd** [rstudio/blogdown#514]
---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

---

**Observation:** RMD post cannot present image rendered with R code

**Steps to reproduce**:

- Create a new post
- Add r-code in the RMD file:

```r
plot(cars)
```

- Save it
- Build site - error shown as below

![error blogdown](https://user-images.githubusercontent.com/17422533/99963729-ca8cd800-2dc4-11eb-93e3-e86d4022f5ad.png)

I used other theme, such as `hugo-lithium` but only `starter-academic` faces this issue - tried development version of blogdown also but the issue still remains unsolved.

**System environment**:

- Windows 10
- R 3.60
- Blogdown 0.21
- Hugo 0.78.2

**Comment by cderv** [comment]
It is possible this is because you have `_files$` in your `ignoreFiles` field in the `config.toml` or `config.yaml`. 

It seems it is put by default when I create a new site with this theme. (I'll look into that). 
Blogdown should now message you something like that in your console 
> You are recommended to remove the item '_files$' in the 'ignoreFiles' field in config.toml.

Can you check and try without this configuration if you have it ?

**Comment by cderv** [comment]
wowchemy/academic is putting `_files$` in `ignoreFiles` by default. 
https://github.com/wowchemy/starter-academic/blob/b14581142c53b6c9dbb4911066c3471f02ce0862/config/_default/config.toml#L37

Blogdown now advice to not set this configuration, because it uses Page bundle structure and you need to have those folder accessible where the post are. Currently I beleive you get the issue because the plots pngs are not taken into account by hugo because of this configuration. 
If you remove `_files$` from the config as blogdown should advice you in the console, it should work. 

This is an issue related to the theme and not blogdown per-se.

**Comment by anhhd** [comment]
Thanks @cderv! I have removed `_files` in `ignoreFiles` and it works normally!
Many thanks @cderv, again! Enjoy your day!
