### ISSUE TITLE
Not seeing Hugo errors print to console

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#536]
Welcome to the blogdown GitHub repo 👋

To file a _bug report_, please follow these instructions carefully: <https://yihui.org/issue/#bug-reports>

I'm not actually sure what is the source of the problem here, but in a brand new fresh R Project with a new site, I'm seeing this locally:

```
> library(blogdown)
> new_site(theme = "victoriadrake/hugo-theme-introduction")
trying URL 'https://github.com/victoriadrake/hugo-theme-introduction/archive/master.tar.gz'
downloaded 20.1 MB

Launching the server via the command:
  /Users/alison/Library/Application Support/Hugo/0.78.2/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-theme-introduction -D -F --navigateToChanged
sh: line 0: kill: (12300) - No such process
Error: It took more than 30 seconds to launch the server. An error might have occurred with hugo. You may run blogdown::build_site() and see if it gives more info. If the site is very large and needs more time to be built, set options(blogdown.server.timeout) to a larger value.
Called from: serve(...)
Browse[1]>
```

When I run `hugo` from the command line, I see:

```
Alisons-MacBook-Pro:introduce-yourself alison$ hugo
Start building sites … 
Total in 355 ms
Error: Error building site: "/Users/alison/rworkshops/introduce-yourself/content/en/blog/configuration.md:58:1": failed to render shortcode "md": failed to process shortcode: "/Users/alison/rworkshops/introduce-yourself/layouts/shortcodes/readfile.html:7:12": execute of template failed: template: shortcodes/readfile.html:7:12: executing "shortcodes/readfile.html" at <readFile>: error calling readFile: file "config.toml" does not exist
Alisons-MacBook-Pro:introduce-yourself alison$ 
```

Looking in the theme, it looks like the `exampleSite` has two sample Hugo shortcodes layouts. I'm not sure why these are problematic?

https://github.com/victoriadrake/hugo-theme-introduction/tree/master/exampleSite/layouts/shortcodes

But aside from that, whenever I get the serve site timeout error, nothing prints to my console, I always need to run `hugo` from the terminal to see an error message.

```
> xfun::session_info()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 1.4.1090

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3        BH_1.72.0.3            blogdown_0.21.60      
  bookdown_0.21          compiler_3.6.1         digest_0.6.27         
  evaluate_0.14          glue_1.4.2             graphics_3.6.1        
  grDevices_3.6.1        highr_0.8              htmltools_0.5.0       
  httpuv_1.5.4           jsonlite_1.7.2         knitr_1.30            
  later_1.1.0.1          magrittr_2.0.1         markdown_1.1          
  methods_3.6.1          mime_0.9               processx_3.4.4        
  promises_1.1.1         ps_1.4.0               R6_2.5.0              
  Rcpp_1.0.5             RcppTOML_0.1.6         rlang_0.4.9           
  rmarkdown_2.6          rstudioapi_0.13.0-9000 servr_0.21            
  stats_3.6.1            stringi_1.5.3          stringr_1.4.0         
  tinytex_0.28           tools_3.6.1            utils_3.6.1           
  xfun_0.19              yaml_2.2.1    
```

---
Aha!

Finally chased the issue down. The shortcodes were being called in `content/en/blog/configuration.md`, and one reads in the file `config.toml`. The exampleSite has a [config.toml](https://github.com/victoriadrake/hugo-theme-introduction/tree/master/exampleSite) file, but I just saw that the default `new_site(format = "yaml")` 😭

Sadly, this did not keep the `config.toml` file:
```
> library(blogdown)
> new_site(theme = "victoriadrake/hugo-theme-introduction", format = "toml")
trying URL 'https://github.com/victoriadrake/hugo-theme-introduction/archive/master.tar.gz'
downloaded 20.1 MB

Launching the server via the command:
  /Users/alison/Library/Application Support/Hugo/0.78.2/hugo server --bind 127.0.0.1 -p 4321 --themesDir themes -t hugo-theme-introduction -D -F --navigateToChanged
sh: line 0: kill: (15098) - No such process
Error: It took more than 30 seconds to launch the server. An error might have occurred with hugo. You may run blogdown::build_site() and see if it gives more info. If the site is very large and needs more time to be built, set options(blogdown.server.timeout) to a larger value.
``` 

Even after copying and pasting the `exampleSite` `config.toml` file manually, I'm just totally stuck:
```
Alisons-MacBook-Pro:introduce-yourself alison$ hugo
Total in 1 ms
Error: module "introduction" not found; either add it as a Hugo Module or store it in "/Users/alison/rworkshops/introduce-yourself/themes".: module does not exist
Alisons-MacBook-Pro:introduce-yourself alison$ 
```

---

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('blogdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the blogdown package using `remotes::install_github('rstudio/blogdown')`?

**Comment by cderv** [comment]
If I add back the `config.toml` in the root folder of the website, then serving the site with `serve_site()` and building with `build_site()`.

Why it does not work with `new_site()` as you've done it ? 
Because I think there is a bug in how the argument are used. 

There are two arguments regarding YAML and TOML in `new_site`: 

* `format` with default to `"yaml"`
* `to_yaml` which default to TRUE 

`format` is used to create the new site (from an empty folder before installing a them)
https://github.com/rstudio/blogdown/blob/b860d27fb475eeb7401fbc0542d46962eeac17b7/R/hugo.R#L145-L148

and `to_yaml` is used to convert the theme files 
https://github.com/rstudio/blogdown/blob/b860d27fb475eeb7401fbc0542d46962eeac17b7/R/hugo.R#L178-L183

You see it is there that the `config.toml` is modified.

Doc says: 
> format	
> The format of the configuration file. Note that the frontmatter of the new (R) > Markdown file created by new_content() always uses YAML instead of TOML or JSON.

> to_yaml	
> Whether to convert the metadata of all posts to YAML

So I believe there is a mistake somewhere (doc or code)

Maybe `to_yaml` is not needed and only `format` can be used (`format = "yaml"` would mean `to_yaml = TRUE`)

About the issue with this theme, this TOML file thing is very specific for this theme as it is because indeed they call the file from within one of the example. 

We could look for `config.toml` in all content files to check if it is safe to delete, but is this something that could happen often ? 

We could also not default to YAML to be sure to have no compatibility with other theme. Using the default config file providing by the theme is the safest at the end. But, yes YAML is more known by user. it is a tradeoff.

**Comment by apreshill** [comment]
I think the default settings are OK. My reading of the docs when I was struggling was that `format`:


format | The format of the configuration file. Note that the frontmatter of the new (R) Markdown file created by new_content() always uses YAML instead of TOML or JSON.
-- | --


So I thought `format` meant config. In hindsight, this would have been much clearer to me if the name was config_format. I assumed "use this arg if you want to convert config.toml -> config.yaml" only.

Then when I read `to_yaml`:

to_yaml | Whether to convert the metadata of all posts to YAML.
-- | --


I think of that as only touching `content/` file metadata. I don't know how I would have discovered that these two args have any dependence on each other?

**Comment by cderv** [comment]
I agree.
I think it should be 
```r
 if (to_yaml) hugo_convert('YAML', unsafe = TRUE)
 if (format == "yaml" && file.exists(cfg <- 'config.toml')) { 
     toml2yaml(cfg, 'config.yaml')
     unlink(cfg) 
   }
```
It is a recent change 
https://github.com/rstudio/blogdown/commit/524b4f289b4a739ec2aa720e46307654c7712730

So I let @yihui decide how he sees it as it was the one adding this toml to yaml conversion

**Comment by apreshill** [comment]
I think it could be useful to show Hugo errors too? As a user, I would rather see something error out than get the server timeout message. I feel like I used to be able to see Hugo errors with blogdown, but now I routinely get the server error and need to run `hugo` to see the error messagee.

**Comment by yihui** [comment]
The dependency between `format` and `to_yaml` was introduced inadvertently. @cderv's fix to the code above was correct and I just applied the fix. `format` is only for `config.yaml/.toml`, and `to_yaml` is only for `content/` now.

When `serve_site()` fails, the error message will suggest you run `blogdown::build_site()`, which will reveal the actual error:

> Error: It took more than 30 seconds to launch the server. An error might have occurred with hugo. You may run blogdown::build_site() and see if it gives more info. If the site is very large and needs more time to be built, set options(blogdown.server.timeout) to a larger value.

I have hoped to improve this but I've been debating with myself what I should do in this case. I could call `blogdown::build_site()` automatically when `serve_site()` fails, but I fear that some users wouldn't like the side-effect of creating or regenerating the `public/` directory. On the other hand, when `serve_site()` fails, I'm not 100% sure if the problem comes from Hugo or the site is just way too big and takes longer than 30 seconds to build (which should be very rare). I'll think more about what I can do. Thanks!

**Comment by yihui** [comment]
The current development version should signal the Hugo error right away:

```r
remotes::install_github('rstudio/blogdown')
```

Thanks for the report!
