### ISSUE TITLE
Not rendering properly 

### ISSUE THREAD

**Issue by jaggaroshu** [rstudio/blogdown#544]
Why it is not rendering the data properly is there any way to solve this issue?

```
a = data.frame(j = c("/*/*//*" , "/***/***/***/"))
kable(a )
```
 output
j
--
/////*
//***/

**Comment by cderv** [comment]
Please can you follow the issue guide (https://yihui.org/issue/) to format the post correctly and also give us enough information so that we understand what you are trying to do, and how. 

Currently, we don't really have enough information. I don't really see the issue i.e what you are trying to do and what results you want.

**Comment by jaggaroshu** [comment]
a = data.frame(j = c("/*/*/*/" , "/***/***/**/"))
kable(a)

j
--
///*/
///**/

**Comment by cderv** [comment]
It is not yet a full reproducible example but I think I understand what is puzzling you. 

You are using `*` in your table which is [a special character](https://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html) in Markdown. It will also happens with any other Markdown character. 
See https://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html

You need to escape this characters with `\`. One when in markdown body in the Rmd (`\*`), two if you are inside a R function (because R needs `\` to be also escaped with `\` so it will be `\\*`. 

See example below for the different way of managing to print the expected table. You'll see there is a few of them. It also depends [what package you are using for your tables](https://bookdown.org/yihui/rmarkdown-cookbook/tables.html). 

here is a reproducible example showing all that

* test.Rmd

`````markdown
---
title: 'Test'
output: 
  html_document: default
---

## Table

Wrong output because `*..*` and `**..**` means something in markdown, so it will be transformed when converting

```{r}
a = data.frame(j = c("/*/*/*/" , "/***/***/**/"))
knitr::kable(a)
```

You need to escape them using `\\`

```{r}
a = data.frame(j = c("/\\*/\\*/\\*/" , "/\\*\\*\\*/\\*\\*\\*/\\*\\*/")) 
knitr::kable(a)
```

This resulting table has been identified for Pandoc to be raw html (so no parsing of markdown syntax inside it)

````{=html}
```{r, echo = FALSE}
# to have a nice html table
library(kableExtra)
a = data.frame(j = c("/*/*/*/" , "/***/***/**/"))
knitr::kable(a, format = "html") %>% kable_styling()
```
````

You can also encapsulate the resulting html table in the syntax to indicate raw html to Pandoc.

```{r, results='asis'}
# to have a nice html table
library(kableExtra)
a = data.frame(j = c("/*/*/*/" , "/***/***/**/"))
res <- knitr::kable(a, format = "html") %>% kable_styling()
cat(
  "```{=html}",
  res,
  "```",
  sep = "\n"
)
```
`````
![image](https://user-images.githubusercontent.com/6791940/103008492-814fb580-4535-11eb-9edf-e9262107ba78.png)


You can also deactivate the extension that lead to pandoc parsing the markdown inside HTML tables. 

````markdown
---
title: 'Test'
output: 
  html_document: 
    md_extension: -markdown_in_html_blocks
---

## Table


```{r}
library(kableExtra)
a = data.frame(j = c("/*/*/*/" , "/***/***/**/"))
knitr::kable(a) %>% kable_styling()
```
````
![image](https://user-images.githubusercontent.com/6791940/103008651-c1af3380-4535-11eb-8d55-2204b00a5564.png)

Some resources you could be interested to understand all this

* Escape special characters: https://bookdown.org/yihui/rmarkdown-cookbook/special-chars.html
* Inserting raw Markdown: https://bookdown.org/yihui/rmarkdown-cookbook/results-asis.html
* Raw HTML in Pandoc Markdown: https://pandoc.org/MANUAL.html#raw-html
* Raw attribute in Pandoc Markdown: https://pandoc.org/MANUAL.html#extension-raw_attribute
