### ISSUE TITLE
Knitting with the Button in the IDE renders HTML even with method != 'html'

### ISSUE THREAD

**Issue by cderv** [rstudio/blogdown#562]
It seems there is something we don't expect in RStudio IDE when using the knit button with blogdown.

blogdown offer different rendering method like 
* method = "custom"
* method = "markdown"

However, even with this method, a HTML is produced when it should not be **only when using the knit button**

This steps should help reproduce 

* Open a new example site to no break anything.
* Use `options(blogdown.method = "custom")` in .Rprofile. This should tell blogdown to let the `build.R` script do the rendering. 
* Restart and check `blogdown:::build_method()` is `"custom"`
* leave `build.R` empty - as do nothing. 
* `blogdown::build_site(build_rmd = TRUE)` will correctly do nothing
* Use the Knit button on a Rmd post => The HTML file will be rendered 

It is the same with `method = "markdown"`

I was under the impression that the Knit button in the IDE would run `rmarkdown::render_site(<absolut_input_path>)` but 

* running `rmarkdown::render_site(<absolut_input_path>)` in the R console will correctly output a .md file
* Clicking on the knit button will run the same function, but in the Rmarkdown pane and will output .html

This happens only with .Rmd to .md - .Rmarkdown are correctly rendered to .markdown. 

It is as if the IDE is modifying the behavior somehow. IDE bug ? 

Discovered in https://github.com/rstudio/blogdown/issues/530

**Comment by cderv** [comment]
@yihui continuing the discussion here. 

I tested with **blogdown** 0.21 and this also happens with `method = "custom"`. 

* using command line does not produce HTML
* using Knit button does produce HTML

**Comment by yihui** [comment]
I've figured out the reason, but don't know what the proper solution should be. When you knit a single Rmd with the Knit button, RStudio starts up the R session in the directory of the Rmd file, instead of the project root. The `.Rprofile` lives in the root, so it's ignored when RStudio starts R from the directory of the Rmd.

**Comment by cderv** [comment]
I tried that to verified that by adding a chunk with `blogdown:::build_method()` and I thought it picked it right... I may have not correctly tested that.

**Comment by yihui** [comment]
It only works with `blogdown.knit.on_save = TRUE` (because in this case, R is started from the root dir). When you click the Knit button, R won't be aware of any settings in `.Rprofile`, so `blogdown.method` will be `NULL`.

**Comment by yihui** [comment]
I just pushed a fix to execute `.Rprofile` when users click the Knit button. I don't really like this hack (e.g., `.Renviron` is also ignored), and would rather have the IDE start R from the project root instead, but I don't know how difficult this change in IDE would be. Besides, even if it is fixed in the IDE, users with older versions of IDE will still have this problem, so my hack has to live in this package anyway for a couple of years.

**Comment by cderv** [comment]
I am not sure to follow completely. What I tried is adding in the Rmd file

````markdown
```{r}
blogdown:::build_method()
```
````

Having this in .Rprofile
```r
options(
  # to automatically serve the site on RStudio startup, set this option to TRUE
  blogdown.serve_site.startup = FALSE,
  # to disable knitting Rmd files on save, set this option to FALSE
  blogdown.knit.on_save = FALSE,
  # build .Rmd to .html (via Pandoc); to build to Markdown, set this option to 'markdown'
  blogdown.method = 'custom'
)
```

And got 
```
blogdown:::build_method()
## [1] "custom"
```

in the HTML produced by the knit button

So I concluded (wrongly it seems) that the method was correctly seen. 

With 
```r
> packageVersion("blogdown")
[1] ‘0.21.81’
```

Would having a configuration file instead of a .Rprofile a solution that would prevent this ? 

I'll try to come up with a reproducible example to add in the list of issue for RStudio IDE.

**Comment by cderv** [comment]
And same thing with custom made option in .Rprofile. 

In fact, I guess this is because we run `render` in its own process using `Rscript_call`and this take care correctly of the .Rprofile. 

Thanks for the quick fix ! One more hack we'll need to maintain then !

**Comment by yihui** [comment]
Oh you are right. It was because `Rscript_call()` launches a new R session: https://github.com/rstudio/blogdown/blob/94d84f9d430d704ec095208d7b2b7d74083a687a/R/render.R#L161

and the new R session is started from the root directory of the project.

**Comment by cderv** [comment]
About the importance of creating good test before coming to a conclusion 😅 
I conclude wrong because my test was... not good - Learning from experience is good!

**Comment by zenggyu** [comment]
I recently ran into a problem described in [this post](https://community.rstudio.com/t/manually-knitting-an-rmd-file-produces-different-results-when-the-file-is-located-at-different-places/115167), and then I found this issue. I guess perhaps this issue is related to the problem but as a novice, I don't quite follow your discussions, so I still can't figure out the solution. I'd really appreciate if you can help! ::laugh::

**Comment by zenggyu** [comment]
Sorry to bother but @cderv would you mind giving some advice? I posted my question on [rstudio community](https://community.rstudio.com/t/manually-knitting-an-rmd-file-produces-different-results-when-the-file-is-located-at-different-places/115167) and [stackoverflow](https://stackoverflow.com/questions/69170758/manually-knitting-an-rmd-file-produces-different-results-when-the-file-is-locate) but haven't received any reply so far.
