### ISSUE TITLE
Site Formatting Rendering with serve_site but not with Netlify

### ISSUE THREAD

**Issue by jschulberg** [rstudio/blogdown#580]
Hi All, I'm having an issue ever since I tried to re-bundle my posts with the new blogdown v0.80.0 that everything looks GREAT locally with serve_site, but the formatting of my articles is stripped when it publishes via Netlify. I feel like I've tried everything I can think of, including rebuilding all of the knitted HTMLs from scratch (which takes a few hours for me), and looked up quite a bit online, but haven't found anything that's solved my issue.

GitHub: https://github.com/jschulberg/DatacracyBlog
Site: https://datacracy.netlify.app/

**Comment by yihui** [comment]
This is likely an issue with Netlify, but we can't see your Netlify deploy log, so I guess there's nothing we could do to help. You could delete the unnecessary `public` directory. Then check the Netlify deploy log.

**Comment by jschulberg** [comment]
@yihui thanks for responding -- I've gotten it to work now! I used check_site() and addressed all the TODO's, which seemed to do the trick. I had to re-build the site by reknitting all the files which took a bit, but everything looks good to go! I'll make sure to use serve_site() to update posts in the future.

I also wanted to thank you for all that you do and have done with blogdown. Being able to create my own blog and showcase my work has not just been a great learning experience, but was a contributing factor to me landing a job during the pandemic. Thank you to you and everyone else who has worked on blogdown for not just making it sleek, but also making it accessible and easy to navigate for users like me!

**Comment by yihui** [comment]
Originally I intended to mention `blogdown::check_site()` (which was also mentioned in the Github issue template), but I briefly looked at your repo and didn't find obvious problems under `content/`. Anyway, I'm glad that `check_site()` helped. Thanks for the kind words!

**Comment by jschulberg** [comment]
Hi all, I hate to reopen a closed issue, but I tried changing my theme to ananke and am running into the exact same issue. `blogdown::check_site()` didn't find any more issues for me. Any guidance would be appreciated!

Site: https://datacracy.netlify.app/
GitHub: https://github.com/jschulberg/DatacracyBlogTake2

**Comment by cderv** [comment]
Hi @jschulberg 

I would say you need to set the full url with protocol and trailing slash in your `config.toml` base_url field.
https://github.com/jschulberg/DatacracyBlogTake2/blob/main/config.toml#L2

Your previous take had this: https://github.com/jschulberg/DatacracyBlog/blob/6b4c3405bfb0245fdf9ca17240f5b34873ef70f5/config.toml#L1

Docs shows full url too: https://bookdown.org/yihui/blogdown/configuration.html
Hugo docs too: https://gohugo.io/getting-started/configuration/#all-configuration-settings

Our demo-site too: https://github.com/rbind/blogdown-demo/blob/cfc0daa3d28a129ff2e65deb94559407f5d8b537/config.toml#L1

So 
```toml
baseURL = "https://datacracy.netlify.app/"
```

We may need to add a check this as I think it is really good practice, if not necessary. Otherwise, it will be considered as relative url.

**Comment by jschulberg** [comment]
Good catch! I just changed it, but to no avail. The site still looks wrong when built via Netlify.

**Comment by yihui** [comment]
Your fix https://github.com/jschulberg/DatacracyBlogTake2/commit/288a20a6b75095d213929f3aa6018ff483ea19d4 was correct. A valid URL [should always include the protocol](https://yihui.org/en/2018/01/valid-url/).

However, I doubt if the site build was successful on Netlify. These two dirs appear to be wrong to me: https://github.com/jschulberg/DatacracyBlogTake2/blob/288a20a6b75095d213929f3aa6018ff483ea19d4/config.toml#L5-L6 I guess Hugo actually failed on Netlify because of them. You should check the build/deploy log on Netlify (https://app.netlify.com).

If the build indeed failed, your site was not actually published after you fixed the problem, so you still have the old site, with the wrong `baseURL`.

BTW, if you intend to build a site on Netlify, there is no need to build the site locally and push the `public/` folder to the Github repo.
