### ISSUE TITLE
[FR] `check_config()` should check for valid URLs

### ISSUE THREAD

**Issue by apreshill** [rstudio/blogdown#616]
Again from my debugging diaries:

```
> blogdown::check_config()
― Checking config.toml
| Checking "baseURL" setting for Hugo...
○ Found baseURL = "openscapes.org"; nothing to do here!
```

the issue was that there was something to do! The `baseURL` should start with `http`- is there a way to check if the `baseURL` is a valid URL?

**Comment by yihui** [comment]
This is actually a hard problem, because in theory, there is no way to tell if `openscrapes.org` is valid or not. This `baseURL` string can be a valid subpath (https://github.com/gohugoio/hugo/issues/7823#issuecomment-707294845) under another domain, e.g., `https://example.org/openscrapes.org/`. `baseURL` doesn't have to start with `http`.

We'll have to use some heuristics to detect "obviously wrong" base URLs, which I think will be helpful, because this seemingly simple problem just confuses too many people (https://yihui.org/en/2018/01/valid-url/).

**Comment by apreshill** [comment]
Oof yes. I wonder if the check could be:

1. level 0- do you have something there that is not just a slash
2. level 1- is it a valid URL? maybe use something like: https://search.r-project.org/CRAN/refmans/RCurl/html/url.exists.html
3. level 2- if not just a slash AND not a valid URL, print essentially: not a valid url, but carry on if using subpaths on purpose!

**Comment by mcanouil** [comment]
Maybe [r-lib/urlchecker](https://github.com/r-lib/urlchecker) could check the base URL?

**Comment by yihui** [comment]
@mcanouil As I said above, the base URL can be just a subpath without the http + domain (e.g., `baseURL: foo/`). That's a valid base URL. In fact, the special case, a single slash `/`, is also a valid base URL. In theory, there is nothing wrong with it and it has its advantages. The main problem is that some RSS readers can't understand it (e.g., R-bloggers).

I tend to fix the most common and confusing issue by heuristics, i.e., when the base URL looks like a domain without the protocol (http). I tend not to validate the URL with `url.exists()` in other cases, since pretty much anything that requires internet connection won't be robust.
