### ISSUE TITLE
`.Rmarkdown` does not show figure with shortcode when `bibliography` in YAML header

### ISSUE THREAD

**Issue by petzi53** [rstudio/blogdown#626]
To reproduce: I used a clean installation of blogdown with the `Xmin` theme. Whenever I include the line
`bibliography: ["references.bib"]` into the YAML header, the Hugo shortcode for a figure did not work. I used an `index.Rmarkdown` file with the following content:

```
---
title: Image-Test
author: Peter
date: '2021-05-25'
slug: image-test
categories: []
tags: []
bibliography: ["references.bib"]
---

{{< figure src="images/my-image.png" >}}
```

In the `index.markdown` file, this resulted in: 

`{{&lt; figure src=“images/my-image.png” &gt;}}`

 Without the bibliography line, the image appeared correctly.

***
I ran all the check functions and have set goldmark:renderer:unsafe to yes. blogdown.method = 'html', but the problem appears also with  blogdown.method = 'markdown'

I am using macOS 11.3.1, Hugo 0.82.0, R 4.1.0, blogdown 1.3, rmarkdown 2.8.

**Comment by petzi53** [comment]
Hello,

Yes, I tried it with the R function to include shortcodes too. It didn't work. The result in the `.markdown` file was no error message, but it just outputs the original line:

`blogdown::shortcode("figure", src = "/images/my-image.png", alt = "A nice figure")`

Please keep in mind that figures in `.Rmarkdown` files are displayed correctly with the normal Hugo shortcode. Only when bibliography is added to the YAML header, then it stops working. So the question is: Why does it stop working with this line? 

The functionality to add bibliographies with `.Rmarkdown` files is a relatively new feature to blogdown. So I suspect that this might be a bug.

**Comment by cderv** [comment]
> Why does it stop working with this line?

this is because when we detect a bibliography field this means than Pandoc needs to be used for citation processing, even if you are output Markdown and not HTML. 

> blogdown::shortcode("figure", src = "/images/my-image.png", alt = "A nice figure")

How did you include it in your document ? in an R chunk like in the [doc](https://bookdown.org/yihui/blogdown/content.html#shortcode) ?
This should evaluate correctly to the shortcode syntax, and you need to set `echo = FALSE` to remove the source code chunk. Like in the doc.

Can you share the document example content ? Something like this

````markdown
---
title: Image-Test
author: Peter
date: '2021-05-25'
slug: image-test
categories: []
tags: []
bibliography: ["references.bib"]
---

```{r, echo = FALSE}
blogdown::shortcode("figure", src = "/images/my-image.png", alt = "A nice figure")
```
````

**Comment by petzi53** [comment]
Hi @cderv 

Sorry, you are right. I was too fast yesterday. Inside an R chunk, it works. How embarrassing 🤭

But what I still do not understand completely: Adding the R chunk with `blogdown::shortcode` as above, the Hugo shortcode for figures does not work anymore! 

Does that mean that it is not the file type as such (`.Rmarkdown` in this case) that matters for the rendering process (Pandoc or Goldmark), but activities that require Pandoc for processing or not? (As you explained to me already with the bibliography problem above.) So the rendering process in the `.Rmarkdown` file is not always the same but conditional? 

That would explain all my questions and the weird behavior as it appeared to me. But in that case, maybe the explanation in the [Announcing blogdown v1.0](https://blog.rstudio.com/2021/01/18/blogdown-v1.0/) article should clarify this issue. After the heading "Better support for Markdown format" one gets the impression that the rendering process is unconditional always the same. For example:

> `.Rmarkdown` files are rendered to `.markdown` using **knitr** and Pandoc, which will then be processed by Hugo Markdown renderer. 

If my understanding is now correct, I must adapt my mental model of how the rendering process works completely. Thank you very much for your help and patience. And sorry for the faux pas with the blogdown shortcode…

**Comment by cderv** [comment]
> Adding the R chunk with blogdown::shortcode as above, the Hugo shortcode for figures does not work anymore!

🤔 This is puzzling. This should work. What is rendered in your `.markdown` output ? Does the shortcode seems correct in this file ? This would help if you share this. Thanks.

I'll also try an example. 

About the rendering process, this is as we tried to express in the table in the post: only file directly written in Markdown `.md` will be processed directly by Goldmark on Hugo. `.Rmd` will output HTML resulting of "md to html" pandoc conversion, so no Hugo Markdown rendering, `.Rmarkdown` will be rendered to `.md` by Pandoc then process by Hugo to HTML in the website. 

We render using Pandoc from .Rmarkdown to .markdown (and not just knit the file) when Pandoc only features (like citation processing or fenced div) are used, Otherwise it would not render correctly. 
So that is the case for bibliography field. I don't think Hugo has support for using bibliography in post, contraty to Pandoc and its citation processing using its internal `--citeproc`. That is why there is this step, and why in a `.Rmd` or `.Rmarkdown` file you need to included shortcodes using this function because Pandoc does not know about this specific syntax. It is not valid Pandoc Markdown. Obviously, you do not have to do that if you are directly writing `.md` file using Hugo markdown syntax (Goldmark)
