### ISSUE TITLE
How to fix error in serve_site :

### ISSUE THREAD

**Issue by carlosgino** [rstudio/blogdown#634]

**Comment by carlosgino** [comment]
blogdown::build_site(build_rmd = 'newfile')
Rendering content/posts/2020-12-01-r-rmarkdown/index.en.Rmd... Done.
Total in 104 ms
Error: from config: 2 error(s) decoding:

* cannot parse 'IsHTML' as bool: strconv.ParseBool: parsing "no": invalid syntax
* cannot parse 'IsPlainText' as bool: strconv.ParseBool: parsing "yes": invalid syntax
>

**Comment by cderv** [comment]
Hi @carlosgino 

We need more information to help you. Have you followed the issue guide ? Did you run `blogdown::check_site()` first ? 

A wild guess from error message (that I did not encounter before): do you have some `yes` / `no` somewhere in a config.yaml or else, and what about changing them to `true` / `false` ? 

This make me thing of changes in YAML spec where `yes` or `no` (and more) were allowed but no more in YAML 1.2 spec - only `true` / `false`. But I don't know which Hugo is using really. 

Can you look and try this in case it works ? 

Otherwise, we need more information about your website and source. I don't think the error you see if from R (blogdown) but more from Hugo directly - and you did not even share the Hugo version you are using. 

Thanks

**Comment by carlosgino** [comment]
Thank you very much for your attention, the problem was Hugo's loveIt theme. As you can see, I just installed the academic theme and it has not been problematic for me. Thank you and sorry for the inconvenience.

blogdown:::serve_site()

Launching the server via the command:
  C:/Users/gigar/AppData/Roaming/Hugo/0.83.1/hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t starter-hugo-academic -D -F --navigateToChanged
Serving the directory . at http://localhost:4321
Launched the hugo server in the background (process ID: 12828). To stop it, call blogdown::stop_server() or restart the R session.
Rendering content/post/2020-12-01-r-rmarkdown/index.en.Rmd... Done.
