### ISSUE TITLE
[FR] bookdown in blogdown

### ISSUE THREAD

**Issue by hardin47** [rstudio/blogdown#641]
I have a bookdown book that exists in the same GitHub repo as my blogdown.

1. The index.html file that gets created when I run bookdown will nicely appear in blogdown (yay for embedding correctly, boo for no table of contents!).  See:

![image](https://user-images.githubusercontent.com/7210585/125703457-89a0005b-6125-4d0e-b96e-484d9bc50d3b.png)

2.  All other html files (created by bookdown) are not embedded in blogdown, although the URL for each of the pages is identical to the structure of the index file.  See (yay for correct table of contents, boo for not embedding within blogdown):

![image](https://user-images.githubusercontent.com/7210585/125703619-ec7f812b-f32b-4499-9515-a2e01fbf38b1.png)

3. In particular, compare the blogdown embedding of the following two URLs:

https://m154-comp-stats.netlify.app/notes/index.html

https://m154-comp-stats.netlify.app/notes/wrang.html

Is this discrepancy in embedding behavior intended or is there a way to make everything have the same behavior?

Thank you!!!

**Comment by yihui** [comment]
Bookdown and blogdown projects are quite independent, e.g., you can't easily share the same navbar across bookdown and blogdown pages, because these pages are generated with totally different mechanisms. Since they are very independent, basically you only have two options: 1) link from one site to another and vice versa; or 2) embed one in another using `<iframe>`. Unfortunately, neither option is optimal (1 means different layouts and structures of the two sites, and 2 is usually bad reading experience). If I must choose one, I'd probably use the first option, i.e., add a link to the book on the blogdown site, and link back to the course site on the bookdown site.

I see that you were using the distill site (https://github.com/hardin47/m154-comp-stats/blob/master/index.Rmd#L5) but what I said above still applies.

**Comment by hardin47** [comment]
Yes, I ended up using the <iframe> option.  It actually seems to work quite well: https://m154-comp-stats.netlify.app/notes.html 

Thank you!!!

**Comment by yihui** [comment]
Great! Thanks for letting me know!
