### ISSUE TITLE
unable to install hugo using blogdown

### ISSUE THREAD

**Issue by u2krazie** [rstudio/blogdown#645]
I am a beginner to blogdown and hugo. I am trying to install hugo using blogdown. 

I have the following error:

![error](https://user-images.githubusercontent.com/44272120/127390778-b40321d7-cbb2-4bdf-abab-44285a81e638.PNG)

Please advise on how to correct this error.

**Comment by yihui** [comment]
@cderv Are you able to reproduce?

**Comment by cderv** [comment]
Hi, 

No I can't reproduce on my windows environment with CRAN version and dev version. 

What is suprising is that we don't specify `exdir` in `unzip` I believe 🤔 

@u2krazie can you share more on the environment in which you are working ? 
Can you retry after being sure of using last version and after the error happens run `traceback()` and post the result here ? 

Thank you !

**Comment by u2krazie** [comment]
Thank you so much for looking into the issue. Many blogdown youtube videos always assume that it's very easy just to install hugo. In the Windows 10 environment, this may not be the case if the PATH enviroment is not set correctly. No matter how much I try I can not install hugo. Believe me, I have spent a lot of hours. Until I saw Mike Dane's 4 year old video on how to install hugo manually (not the current method of chocolaty). In it he showed how to set the Path variables. After I did this, blogdown was able to verify that I have hugo running.

**Comment by cderv** [comment]
Thanks for the update. 

`blogdown::install_hugo()` should be really simple and straightforward. No PATH, it will download directly a bundle to a location known by **blogdown** on Windows 10. So there would be not PATH to set up. 

The error you have about installing is difficult to diagnose without further information. If you stumble upon this issue again, please reach out so that we can help and try be sure this is fixed. 

Glad it works for you now!
