### ISSUE TITLE
[FR] Easily add a search bar

### ISSUE THREAD

**Issue by rtheodoro** [rstudio/blogdown#660]
HI ! Thanks for your package, it's awesome!

I would like to put a search bar in my blog.

 I found this:  https://gohugo.io/tools/search/ 
But I was not able to implement with this because I basically only know R.

I would be nice if the package have this option.

**Comment by yihui** [comment]
Just FYI, I wrote a blog post last year on this feature: https://yihui.org/en/2023/09/fuse-search/ It's a dedicated search page (like [this](https://yihui.org/search/)) instead of a search bar. The latter could be implemented but does have some extra complexity. Personally I prefer a separate search page instead of a search bar on each page.

**Comment by rtheodoro** [comment]
Thanks a lot!
