### ISSUE TITLE
Way to "freeze" post?

### ISSUE THREAD

**Issue by xvrdm** [rstudio/blogdown#68]
Is there a recommended way to "freeze" a post? For example, I have a post describing some scraping operations, which might fail in the future if the target page change. I would like Hugo/blogdown to rerender the code inside the page only on demand. If the page could still reflect changes to the template without modifying the output of the R snippets, it would be even better.

(thanks for the awesome library, it's the easiest way to blog with R I have tried by far)

**Comment by yihui** [comment]
Two approaches:

1. Turn on the chunk option `cache=TRUE` on code chunks that should not be executed every time; however, the cache may be invalidated accidentally due to a number of factors.

2. As long as the .html output is not older than .Rmd, the Rmd file will not be recompiled. See more at https://bookdown.org/yihui/blogdown/methods.html

Either way, the page will always reflect changes to your Hugo template.

**Comment by xvrdm** [comment]
Thanks a lot!

(for future ref, I found your doc on cache here: https://yihui.name/knitr/options/)
