### ISSUE TITLE
blogdown's own website partially broken

### ISSUE THREAD

**Issue by r2evans** [rstudio/blogdown#680]
The `blogdown` website itself looks different in FF-95.0.2 (win11) based on the presence of a trailing `/`:

- Without trailing `/`, ***as linked from CRAN***. None of the links ("Get started", ..., "Reference") works, all 404.
    
![image](https://user-images.githubusercontent.com/5815808/148256148-d986fd50-fd86-4071-9f66-be23effa7868.png)

- With trailing `/`, all burger-menu links work:
    
![image](https://user-images.githubusercontent.com/5815808/148256334-af0db740-fee9-4cbc-a7a2-19f6dd77532b.png)

With the former, browser-console reports 404s on most but not all `.js` and `.css`. One such failure:

- without trailing `/`, `jquery-3.6.0.min.js` is attempting to download 

    ```
    GET https://pkgs.rstudio.com/deps/jquery-3.6.0/jquery-3.6.0.min.js
    ```

- without trailing `/`, 

    ```
    GET https://pkgs.rstudio.com/blogdown/deps/jquery-3.6.0/jquery-3.6.0.min.js
    ```

**Comment by yihui** [comment]
@r2evans Thanks for the report! I just updated the URL in DESCRIPTION.

@cderv I remember we fixed this issue long time ago (by automatically adding the trailing slash if not present)? I'm not sure why it's still a problem.

**Comment by cderv** [comment]
🤔 I should indeed be working.
The feature has been put inside **pkgdown** now, and I switche the **blogdown** website to the new template recently that use the last **pkgdown**. 

However there is a typo in here: https://github.com/rstudio/blogdown/blob/fb803c4078bd729104a25c976d1e149833c8a71a/_pkgdown.yml#L11
because there is a typo is the NEWS file
https://pkgdown.r-lib.org/news/index.html#html-css-and-js-2-0-0

It should be `trailing_slash_redirect`
https://github.com/r-lib/pkgdown/blob/dcec859cab08ff8852f5ee5ab09f3f57ec038805/R/build-home-index.R#L49

as in the doc
https://pkgdown.r-lib.org/reference/build_site.html#template

I'll fix this. 

I don't remember what, but it is possible the trailing slash in the URL field for DESCRIPTION are causing other issues 🤔

**Comment by cderv** [comment]
This is now fix and working correctly. 

Thanks for the report @r2evans ! 

@yihui I have updated our template in **quillt** and also the other website that I already migrated. I did not revert the trailing slash addition in DESCRIPTION.

**Comment by yihui** [comment]
Okay, thanks!
