### ISSUE TITLE
GitLab and htmlwidgets Support?

### ISSUE THREAD

**Issue by phillc73** [rstudio/blogdown#7]
I have to admit to not actually trying to install this yet, but the README suggests a requirement for a GitHub account. I was wondering if this will work with GitLab, specifically in the first instance gitlab.com too?

I'm really looking forward to seeing how this develops. I've been wanting to move one site from Jekyll to Hugo, and launch another in Hugo, but put it in the later basket without RMarkdown/knitr/RStudio support.

Easy support for [htmlwidgets](http://www.htmlwidgets.org/) would also be really appreciated. At the moment I have [DT](https://github.com/rstudio/DT) and [metricsgraphics](https://github.com/hrbrmstr/metricsgraphics) integrated in my Jekyll site following the process outlined in [this blog post](https://brendanrocks.com/htmlwidgets-knitr-jekyll/).

**Comment by yihui** [comment]
No, a Github account is not required. It is only that Hugo itself and most Hugo themes are on Github, so they will be downloaded from Github. Other than that, this package is independent with Github (of course, the R package source is hosted on Github). So yes, you are free to use Gitlab or whatever.

I have been using Jekyll myself for several years and I was frustrated time and time again. I chose Hugo this time for many reasons, and I had very similar experience with the author of Hugo (WordPress, Jekyll, ...): https://gohugo.io/overview/introduction/ The short answer to your question is yes, HTML widgets are supported out of the box! No need to hack at anything on your side. Feel free to use any widgets in R code chunks.

**Comment by phillc73** [comment]
Thanks! This sounds really exciting. I'll give it a try over the weekend.

**Comment by good-marketing** [comment]
Hi Yihui,

I just have to say this package rocks. I 've been searching  / hacking together a solution to be able to use RMarkdown for blogpost for some time. I hooked up my blogdown git to AWS ( thanks to https://alestic.com/2016/10/aws-git-backed-static-website/) and can now test, commit and push source and publish content in one go. Including htmlwidgets, which work great, see example here https://d1te751w1n8heu.cloudfront.net/post/hello-world/. Really a nice, clean workflow where one can focus on content, not process. Thanks so much!

Bob

**Comment by yihui** [comment]
@good-marketing I'm very glad to hear that. There are still many rough edges in this package, but it should work reasonably well for most users now, even though I just started working on this project a few weeks ago. I'm equally excited about it, but let's hold the excitement for a few more weeks and not to advertise it until I feel 90% of the work is done. It is totally fine if you play with it by yourself or tell a few friends, and I'll truly appreciate your feedback as a very early tester.

**Comment by dfalbel** [comment]
I really like this package too! Thanks @yihui !!

**Comment by thedatacollective** [comment]
@phillc73 did you manage to get things deploying alright with gitlab CI? I've been trying out blowdown and can create things locally, however if I don't push my `public` folder to the gitlab then none of my `.Rmd` posts get rendered. 

I suspect this may be because the get built in the `blogdown/post` folder rather than the `content/post` folder.

Anyone have thoughts on how to get this working (i.e. to have the `.md` and `.html` files in the `content/post` folder)? I followed the instructions [here](https://gohugo.io/tutorials/hosting-on-gitlab/) to build out the `.gitlab-ci.yml` file.

I have an example repo on github that can be found [here](https://github.com/thedatacollective/blogtest)

**Comment by thedatacollective** [comment]
I have figured out how to make this work with gitlab.com after several rounds of trial and error, using various `rocker` images in the `.gitlab-ci.yml` file and various scripts.

Nothing seemed to work at first. Either the CI would fail, or it would succeed but the blog would only have the header & footer of the page with no content for the `index.html` page.

Finally I thought more simply. Use `build_site()` or `serve_site` to generate the `public` folder and then just allow that to be copied to the gitlab pages location.

Below is an example of my `.gitlab-ci.yml` in the hope that it helps someone in future.

``` {YAML} 
pages:
  script:
    - ls
  artifacts:
    paths:
    - public
  only:
  - master
```
The reason I've got the script with `ls` is because gitlab doesn't allow the script to be empty so I needed a command that could do something without affecting things.

I will finally say that I do push everything to my repository (including `public` folder) but I may end up trying a branch in future that is just to publish that contains the public directory.
