### ISSUE TITLE
rendering issue with hugo_book theme

### ISSUE THREAD

**Issue by ghost** [rstudio/blogdown#709]
I have the following chunk in the `post` of this theme (https://github.com/alex-shpak/hugo-book).

````
```{r pie, fig.cap='A fancy pie chart.'}
par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c('Sky', 'Sunny side of pyramid', 'Shady side of pyramid'),
  col = c('#0292D8', '#F7EA39', '#C4B632'),
  init.angle = -50, border = NA
)
```
````

The HTML outcome became this:

```html
<div class="figure"><span style="display:block;" id="fig:pie"></span>
<img src="{{< blogdown/postref >}}index_files/figure-html/pie-1.png" alt="A fancy pie chart." width="672" />
<p class="caption">
Figure 1: A fancy pie chart.
</p>
</div>
```

The problem of it is: there is no plot on my blog.  I had to go into the HTML file, manually removed `{{< blogdown/postref >}}`.

**Comment by yihui** [comment]
You shouldn't need to remove `{{< blogdown/postref >}}`. I cannot reproduce your problem after I create a new site with `blogdown::new_site(theme = "alex-shpak/hugo-book")`. Please make sure that you follow [the issue guide](https://github.com/rstudio/blogdown/issues/new?assignees=&labels=&template=bug-report.md&title=) to provide the required information when filing an issue, otherwise it can be very difficult for us to help you. Thanks!
