### ISSUE TITLE
Shadocs theme issue

### ISSUE THREAD

**Issue by pensivedog** [rstudio/blogdown#712]
Looking for help using the [Shadocs](https://github.com/jgazeau/shadocs) theme with blogdown. I've had no problem with other themes, but this one is giving the following error when I try to serve or build the site:

Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:1:2: executing "_default/single.html" at <partial "main.html" (dict "root" . "contentTemplate" "theme/content.html")>: error calling partial: execute of template failed: template: partials/main.html:4:4: executing "partials/main.html" at <partial "theme/includes-head.html" .root>: error calling partial: "G:\me\themes\shadocs\layouts\partials\theme\includes-head.html:21:10": execute of template failed: template: partials/theme/includes-head.html:21:10: executing "partials/theme/includes-head.html" at <.>: range can't iterate over css/shortcuts.css

I reported this [here](https://github.com/jgazeau/shadocs/issues/62), but was unable to resolve it.

Any idea how I can get it working?

**Comment by yihui** [comment]
See my reply here: https://github.com/jgazeau/shadocs/issues/62#issuecomment-1171663055

I guess I won't have time to fix this issue, but it shouldn't be too hard. In case someone wants to help, below is what you could do:

1. After the theme is downloaded, check if the file `.gitmodules` exists:
https://github.com/rstudio/blogdown/blob/1c2a6b697a50cd447ddaeb8720adecd0a341e0e9/R/hugo.R#L339-L341
1. If it does, read its content, which looks like this:
    ```
    [submodule "assets/bulma"]
	    path = assets/bulma
	    url = https://github.com/jgthms/bulma.git
    ```
1. Run `git clone` on the `url`, and clone the submodule to `path`.

The above method may not be reliable because it is not actually how Git submodules work. We should download a specific SHA of the module instead. An alternative and more robust method is to `git clone --recursive` the theme repo when `.gitmodules` is detected. A small downside of this method is that it requires `git` (we could use `git` wrapper packages in R, too, if any is installed).

**Comment by pensivedog** [comment]
A separate issue I'm having with this theme (including here so as to not have multiple issues related to this particular theme in the issue queue):

Knitting an Rmd file that includes an interactive plot using htmlwidgets fails to render the plot in the outputted html, and the associated _files folder is automatically deleted.

I'm currently trying to get a simple plot to display in a test.Rmd file with the following content:

````{r test, echo=FALSE, message=FALSE, warning=FALSE}

plot_ly(economics, x = ~date, y = ~pop)

````

**Comment by yihui** [comment]
I can't reproduce your problem. Have you run `blogdown::check_site()`?

**Comment by pensivedog** [comment]
Thank you for trying. Yes, I have tried running `blogdown::check_site()` and everything looks fine.

This is perplexing - I'm able to reproduce it without fail. With other themes I've tried, it simply works as expected. When testing with the Shadocs theme, I can see the test_files folder generated while knitting, then it disappears as the knitting completes, leaving just the test.html file without its dependencies.

I've tried several times creating new blogdown projects using Shadocs and other themes, and this is only happening with Shadocs. 

Here are my exact steps to reproduce it:

1. Create new project using Shadocs theme
2. Copy files to `themes/shadocs/assets/bulma` as described [here](https://github.com/jgazeau/shadocs/issues/62)
3. Add square brackets around `css/shortcuts.css` and `js/shortcuts.js` in `config.yaml` as described in above issue
4. Initialize git and make a commit
5. Create a test.Rmd file anywhere in the `content` folder or one of its subfolders with the following content:

```{r setup, include=FALSE, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#load libraries
library(htmlwidgets)
library(plotly)
```

```{r test, echo=FALSE, message=FALSE, warning=FALSE}
plot_ly(economics, x = ~date, y = ~pop)
```
6. Knit test.Rmd

**Comment by yihui** [comment]
If you create `test.Rmd`, the `_files/` directory will be automatically moved to the `static/` folder under the site root directory. That's expected, and it should work when you build or serve the site. If you create `test/index.Rmd`, the `_files` won't be moved.

Per instructions at https://bookdown.org/yihui/blogdown/workflow.html, you are strongly recommended to serve the site instead of hitting the Knit button. And I also recommend that you use the "New Post" addin to create new posts.

**Comment by yihui** [comment]
> This might be acceptable for a site with few pages, but would necessitate a pretty inconvenient directory structure for sites with many pages.

I don't understand why that would be inconvenient for many pages.

If you mean converting all `page.Rmd` to `page/index.Rmd`, there is a convenience function `blogdown::bundle_site()` to help you.

> Any tips on how I can get pages built from `.Rmd` files with names other than `index` to successfully render plots using the Shadocs theme?

I investigated this problem and found the culprit to be the `module` configuration in `config.yaml`, which seems to have messed up the `static/` directory. Either deleting the `module` config or adding a `source`/`target` pair could fix the problem:

```yaml
module:
  hugoVersion:
    extended: yes
    max: ''
    min: 0.71.0
  mounts:
    - source: openapi
      target: static/openapi
    - source: static
      target: static/
```

but honestly I don't really know much about Hugo modules. Personally I'd still recommend using `index.Rmd` so that the `static/` directory will not be used at all.

> As an aside, using blogdown's "New Post" addin to create new posts in Shadocs doesn't create the post in the expected location. For instance, choosing Subdirectory to be `english/post` and "test" as the Post Title generates the Filename in the addin `english/post/2022-07-04-test/index.en.Rmd`, but the addin actually creates the file at `content/english/english/post/2022-07-04-test/index.en.Rmd` - with an extra "english" in the file path.

That sounds like a bug. I'll see if I can fix it. Thanks for the report!

**Comment by pensivedog** [comment]
This works great. Thank you again!

**Comment by yihui** [comment]
> As an aside, using blogdown's "New Post" addin to create new posts in Shadocs doesn't create the post in the expected location. For instance, choosing Subdirectory to be `english/post` and "test" as the Post Title generates the Filename in the addin `english/post/2022-07-04-test/index.en.Rmd`, but the addin actually creates the file at `content/english/english/post/2022-07-04-test/index.en.Rmd` - with an extra "english" in the file path.

I have fixed this problem. You can test the development version via

```r
remotes::install_github('rstudio/blogdown')
```

**Comment by pensivedog** [comment]
Problem solved!
