### ISSUE TITLE
failed to extract shortcode: template for shortcode "fragment" not found

### ISSUE THREAD

**Issue by PsyYaoxiaoqiang** [rstudio/blogdown#723]
Launching the server via the command:
  C:/Users/psyyxq/AppData/Roaming/Hugo/0.101.0/hugo.exe server --bind 127.0.0.1 -p 4321 --themesDir themes -t starter-hugo-academic -D -F --navigateToChanged
Error: Error building site: "C:\Users\psyyxq\Documents\myprojects\CV\Academic-resume\content\slides\example\index.md:83:1": failed to extract shortcode: template for shortcode "fragment" not found

what does this mean and how to solve it？

**Comment by yihui** [comment]
This might be a bug of the wowchemy theme: https://github.com/wowchemy/wowchemy-hugo-themes/commit/b49528cf1e812b0136be7f35540573b357c8c6b9#commitcomment-81429105 I can't do much for you before the author fixes it. You may take a look at this theme and see if you like it: https://github.com/hugo-apero/hugo-apero

**Comment by PsyYaoxiaoqiang** [comment]
> This might be a bug of the wowchemy theme: [wowchemy/wowchemy-hugo-themes@b49528c#commitcomment-81429105](https://github.com/wowchemy/wowchemy-hugo-themes/commit/b49528cf1e812b0136be7f35540573b357c8c6b9#commitcomment-81429105) I can't do much for you before the author fixes it. You may take a look at this theme and see if you like it: https://github.com/hugo-apero/hugo-apero

Many thanks！

**Comment by yihui** [comment]
If you can't wait for the fix, you can

1. download https://github.com/wowchemy/wowchemy-hugo-themes/archive/refs/heads/main.zip and unzip it;
2. copy the [wowchemy-plugin-reveal](https://github.com/wowchemy/wowchemy-hugo-themes/tree/main/modules/wowchemy-plugin-reveal) folder to your `themes/github.com/wowchemy/wowchemy-hugo-themes/modules/` directory;
3. add `- path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-plugin-reveal` under `module: imports:` in [config/_default/config.yaml](https://github.com/wowchemy/starter-hugo-academic/blob/5ec3c5dc898d931ec4bf7fd303e632ef50bb20c1/config/_default/config.yaml#L23).

I'm closing this issue for now, since it's a theme instead of **blogdown** issue.
