### ISSUE TITLE
Why are tabs replaced with spaces in code blocks

### ISSUE THREAD

**Issue by amarakon** [rstudio/blogdown#740]
If I add a code block in an R Markdown document, the resulting Markdown file will have tabs replaced with four spaces in that code block. I don't know why this is the default behaviour, and I wish there was a way to change it. Is there currently a way to make it so that tabs are preserved in code blocks? And why are they not by default?

As a reference, see this topic on community.rstudio.com: https://community.rstudio.com/t/how-can-i-prevent-r-markdown-from-turning-tabs-to-spaces-in-code-blocks/152691/8

## Checklist

When filing a _bug report_, please check the boxes below to confirm that you have provided us with the information we need. Have you:

- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('rmarkdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the rmarkdown package using `remotes::install_github("rstudio/rmarkdown")`?

---

Output of `xfun::session_info("rmarkdown")`:

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Gentoo Linux

Locale:
  LC_CTYPE=en_CA.utf8       LC_NUMERIC=C
  LC_TIME=en_CA.utf8        LC_COLLATE=en_CA.utf8
  LC_MONETARY=en_CA.utf8    LC_MESSAGES=C
  LC_PAPER=en_CA.utf8       LC_NAME=C
  LC_ADDRESS=C              LC_TELEPHONE=C
  LC_MEASUREMENT=en_CA.utf8 LC_IDENTIFICATION=C

Package version:
  bslib_0.4.1     evaluate_0.18   htmltools_0.5.3 jquerylib_0.1.4
  jsonlite_1.8.3  knitr_1.41      methods_4.2.1   rmarkdown_2.18
  stringr_1.4.1   tinytex_0.42    tools_4.2.1     utils_4.2.1
  xfun_0.35       yaml_2.3.6

Pandoc version: 2.19.2
```

**Comment by yihui** [comment]
I don't want to make this too general and complicated, but just added `--preserve-tabs` to the default value of `pandoc_args`. I don't think this is an option that is going to be widely used, so I tend to keep it simple for now. Thanks!

BTW, if anyone doesn't like this change (i.e., prefers tabs to be replaced by spaces), they have two choices. One is to use spaces instead of tabs in the input document, and the other is to provide custom `pandoc_args` values to `blogdown::html_page`. I guess the demand should be rare.
