### ISSUE TITLE
Website differs in layout depending on "www"

### ISSUE THREAD

**Issue by larnsce** [rstudio/blogdown#77]
Depending on entering http://lse.de/r-tistic/ or http://www.lse.de/r-tistic/ the layout differs. The first is the layout that I expect and the second seems to not use some of CSS styles. I am using `baseurl = http://lse.de/r-tistic/` in the `config.toml`

**Comment by yihui** [comment]
This issue is not specific to blogdown, so StackOverflow will be a better place to ask. I don't have the time to explain the technical detail, but when in doubt, look at the console:

![image](https://cloud.githubusercontent.com/assets/163582/24277516/7ee644e8-100b-11e7-943e-e6d5caa7da7b.png)

You'd better make a hard decision whether you want www or not, and stick with the decision. Then 301 redirect the other URL to the one you choose (from www to apex or apex to www). As I have already warned you in #52, setting `baseurl` and `relativeurls = false` is not a good idea in my eyes. You could have avoided this issue if you took my advice.

**Comment by Larnsce** [comment]
Thanks a lot, Yihui, and my apologies for not listening to you in the first place. Now that I have added `layouts/partials/disqus.html` it works perfectly.
