### ISSUE TITLE
suppress the warning message on the R console screen?

### ISSUE THREAD

**Issue by likanzhan** [rstudio/blogdown#90]
I have suppressed the warning message with the  option`warning = FALSE` in the rmd file. 
But when I build the site with `blowdown::build_site()`, the warning message is still printed on the R console screen. 
It is really annoying, I'm wondering if there is a way to suppress the warning message on the R console screen?
Thanks

**Comment by yihui** [comment]
You have to use `suppressWarnings()` on the expression that generated the warnings. `warning=FALSE` only means the warnings are suppressed in your R Markdown output (HTML).

Or if you want to suppress all warnings, set `options(warn = -1)` [in .Rprofile](https://bookdown.org/yihui/blogdown/global-options.html), which is a bad idea, because sometimes warnings may be important and you cannot blindly ignore them.

**Comment by likanzhan** [comment]
Thanks
